/**
 * Report templates with formatting
 */

export const REPORT_TEMPLATES = {
  royaltyRoll: {
    title: 'Royalty Roll Report',
    header: ['Unit', 'Site', 'Monthly Royalty', 'Status', 'Buyer'],
    footer: 'Generated by BORJIE Reports',
  },
  collection: {
    title: 'Collection Report',
    header: ['Date', 'Amount', 'Reference', 'Customer'],
    footer: 'Generated by BORJIE Reports',
  },
  assetUtilisation: {
    title: 'Asset Utilisation Report',
    header: ['Site', 'Total Units', 'Producing', 'Asset Utilisation %'],
    footer: 'Generated by BORJIE Reports',
  },
  maintenance: {
    title: 'Maintenance Report',
    header: ['Category', 'Count', 'Cost'],
    footer: 'Generated by BORJIE Reports',
  },
  financial: {
    title: 'Financial Summary',
    header: ['Metric', 'Value'],
    footer: 'Generated by BORJIE Reports',
  },
  buyerStatement: {
    title: 'Buyer Statement',
    header: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    footer: 'Generated by BORJIE Reports',
  },
  sitePerformance: {
    title: 'Site Performance',
    header: ['Metric', 'Value'],
    footer: 'Generated by BORJIE Reports',
  },
} as const;

/**
 * Format a money amount using the caller-supplied currency + locale.
 * There is no KES/en-KE default — callers MUST pass the tenant's
 * currency and locale (resolved from region-config) so multi-tenant
 * reports don't silently render as KES for non-Kenya tenants.
 */
export function formatCurrency(
  amount: number,
  currency: string,
  locale: string = 'en'
): string {
  return new Intl.NumberFormat(locale, { style: 'currency', currency }).format(amount);
}

export function formatPercent(value: number): string {
  return `${value.toFixed(1)}%`;
}

export function formatDate(date: Date, locale: string = 'en'): string {
  // ISO day-precision format is locale-independent by design.
  void locale;
  return date.toISOString().slice(0, 10);
}
