/**
 * Finance-related glossary (mining-fiscal vocabulary).
 *
 * Royalty / clearing-fee / valuation / offtake-proceeds vocabulary is
 * used across the treasury workflows, the royalty-return drafter, and
 * owner-facing reporting, so curation quality here has direct
 * downstream impact.
 *
 * Tanzania-first: domestic settlement is in TZS; USD appears only on
 * the export / offtake leg. Royalty is 6% on the gross value of metallic
 * minerals and gemstones, plus a 1% clearing fee at the point of sale
 * or export (Mining Act, 2010, as amended 2017).
 */

import { buildEntries, enOnlyBatch, type EntrySpec } from './helpers.js';
import type { GlossaryEntry } from '../types.js';

const CORE_SPECS: readonly EntrySpec[] = [
  {
    id: 'finance.royalty',
    en: 'royalty',
    def: 'The statutory levy payable to the State on the gross value of minerals produced — 6% for metallic minerals and gemstones in Tanzania.',
    cat: 'finance',
    juris: ['TZ', 'KE', 'GH', 'ZA', 'AU', 'CD', 'ZM'],
    t: {
      sw: 'mrabaha',
      ar: 'إتاوة التعدين',
      fr: 'redevance minière',
      de: 'Förderabgabe',
      ko: '광업 로열티',
      ja: '鉱業ロイヤルティ',
      pt: 'royalty mineiro',
      es: 'regalía minera',
      zh: '矿业权使用费',
      hi: 'खनिज रॉयल्टी',
    },
    cite: { jurisdiction: 'TZ', statuteRef: 'Mining Act', section: 's.87', year: 2010 },
  },
  {
    id: 'finance.clearing_fee',
    en: 'clearing fee',
    def: 'A 1% inspection charge on the value of minerals at the point of sale or export, payable in addition to royalty.',
    cat: 'finance',
    juris: ['TZ'],
    t: {
      sw: 'ada ya ukaguzi wa madini',
      ar: 'رسوم التخليص',
      fr: 'frais de dédouanement minier',
      de: 'Abfertigungsgebühr',
      ko: '광물 통관 수수료',
      ja: '鉱物クリアリング手数料',
      pt: 'taxa de inspeção',
      es: 'tasa de despacho',
      zh: '清关费',
      hi: 'क्लियरिंग शुल्क',
    },
    cite: { jurisdiction: 'TZ', statuteRef: 'Mining Act', section: 's.89', year: 2017 },
  },
  {
    id: 'finance.gross_value',
    en: 'gross value',
    def: 'The market value of minerals at the point of refining or sale, used as the base on which royalty is computed.',
    cat: 'finance',
    juris: ['TZ', 'KE', 'GH', 'ZA'],
    t: {
      sw: 'thamani ya jumla ya madini',
      ar: 'القيمة الإجمالية',
      fr: 'valeur brute',
      de: 'Bruttowert',
      ko: '총 가치',
      ja: '総価値',
      pt: 'valor bruto',
      es: 'valor bruto',
      zh: '总价值',
      hi: 'सकल मूल्य',
    },
    cite: { jurisdiction: 'TZ', statuteRef: 'Mining Act', section: 's.87(2)', year: 2010 },
  },
  {
    id: 'finance.offtake_proceeds',
    en: 'offtake proceeds',
    def: 'Revenue received from the sale of mineral output under a spot sale or a forward offtake agreement.',
    cat: 'finance',
    juris: ['TZ', 'KE', 'GH', 'ZA', 'AU', 'CD', 'ZM'],
    t: {
      sw: 'mapato ya mauzo ya madini',
      ar: 'عائدات البيع',
      fr: "produit de l'enlèvement",
      de: 'Abnahmeerlös',
      ko: '인수 대금',
      ja: 'オフテイク収入',
      pt: 'receita de aquisição',
      es: 'ingresos por venta',
      zh: '包销收入',
      hi: 'ऑफटेक आय',
    },
  },
  {
    id: 'finance.export_proceeds',
    en: 'export proceeds (USD)',
    def: 'Foreign-currency receipts from exported minerals; the only leg where USD settlement is expected for a TZ-jurisdiction operation.',
    cat: 'finance',
    juris: ['TZ', 'GH', 'ZA', 'CD', 'ZM'],
    t: {
      sw: 'mapato ya mauzo ya nje (USD)',
      ar: 'عائدات التصدير',
      fr: "produit d'exportation",
      de: 'Exporterlös',
      ko: '수출 대금',
      ja: '輸出代金',
      pt: 'receita de exportação',
      es: 'ingresos de exportación',
      zh: '出口收入',
      hi: 'निर्यात आय',
    },
  },
  {
    id: 'finance.export_levy',
    en: 'mineral export levy',
    def: 'A statutory levy on the value of exported minerals, charged in addition to royalty and the clearing fee.',
    cat: 'finance',
    juris: ['TZ', 'GH'],
    t: {
      sw: 'ushuru wa mauzo ya nje ya madini',
      ar: 'ضريبة تصدير المعادن',
      fr: "taxe à l'exportation de minéraux",
      de: 'Mineralexportabgabe',
      ko: '광물 수출세',
      ja: '鉱物輸出課徴金',
      pt: 'imposto de exportação mineral',
      es: 'gravamen de exportación mineral',
      zh: '矿产出口税',
      hi: 'खनिज निर्यात उपकर',
    },
  },
  {
    id: 'finance.valuation',
    en: 'mineral valuation',
    def: 'Government assay-based assessment of a mineral consignment to fix the royalty base and clearing charge before sale or export.',
    cat: 'finance',
    juris: ['TZ', 'GH'],
    t: {
      sw: 'uthamini wa madini',
      ar: 'تقييم المعادن',
      fr: 'évaluation des minéraux',
      de: 'Mineralbewertung',
      ko: '광물 평가',
      ja: '鉱物評価',
      pt: 'avaliação mineral',
      es: 'valoración mineral',
      zh: '矿产估值',
      hi: 'खनिज मूल्यांकन',
    },
  },
  {
    id: 'finance.gepg',
    en: 'GePG control number',
    def: 'A Government electronic Payment Gateway reference used to remit royalty, fees, and levies to the Treasury.',
    cat: 'finance',
    juris: ['TZ'],
    t: {
      sw: 'namba ya kudhibiti malipo (GePG)',
      ar: 'رقم تحكم GePG',
      fr: 'numéro de contrôle GePG',
      de: 'GePG-Kontrollnummer',
      ko: 'GePG 관리번호',
      ja: 'GePG管理番号',
      pt: 'número de controlo GePG',
      es: 'número de control GePG',
      zh: 'GePG 控制号',
      hi: 'GePG नियंत्रण संख्या',
    },
    notes: 'GePG = Government electronic Payment Gateway; royalty and licence fees are paid against a generated control number.',
  },
  {
    id: 'finance.annual_rent',
    en: 'annual mineral-right rent',
    def: 'Per-hectare ground rent payable yearly to keep a mineral right in good standing, distinct from royalty on production.',
    cat: 'finance',
    juris: ['TZ', 'GH', 'ZA'],
    t: {
      sw: 'kodi ya mwaka ya eneo la madini',
      ar: 'الإيجار السنوي للحق المعدني',
      fr: 'redevance superficiaire annuelle',
      de: 'jährliche Feldesabgabe',
      ko: '연간 광구세',
      ja: '年間鉱区使用料',
      pt: 'taxa anual de superfície',
      es: 'canon anual de superficie',
      zh: '年度矿区使用费',
      hi: 'वार्षिक क्षेत्र किराया',
    },
  },
  {
    id: 'finance.tra_assessment',
    en: 'TRA tax assessment',
    def: 'Tanzania Revenue Authority assessment of corporate income tax and withholding tax on mining income.',
    cat: 'finance',
    juris: ['TZ'],
    t: {
      sw: 'makadirio ya kodi ya TRA',
      ar: 'تقدير الضريبة TRA',
      fr: "avis d'imposition TRA",
      de: 'TRA-Steuerbescheid',
      ko: 'TRA 세금 부과',
      ja: 'TRA税額査定',
      pt: 'liquidação fiscal TRA',
      es: 'liquidación tributaria TRA',
      zh: 'TRA 税务评估',
      hi: 'TRA कर निर्धारण',
    },
  },
];

const EXTRA_ROWS: ReadonlyArray<readonly [string, string, string, ReadonlyArray<string>?]> = [
  ['finance.invoice', 'invoice', 'Itemised statement of charges sent to a buyer or counterparty.'],
  ['finance.receipt', 'receipt', 'Written acknowledgement of payment received.'],
  ['finance.statement', 'statement of account', 'Periodic summary of charges and payments on an account.'],
  ['finance.ledger', 'ledger', 'Chronological record of financial transactions on an account.'],
  ['finance.reconciliation', 'reconciliation', 'Matching of internal records against a counter-party or assay statement.'],
  ['finance.write_off', 'write-off', 'Accounting action to derecognise a receivable deemed uncollectable.'],
  ['finance.accrual', 'accrual', 'Expense or revenue recognised before cash movement.'],
  ['finance.prepayment', 'prepayment', 'A payment made before the obligation it relates to falls due.'],
  ['finance.overpayment', 'overpayment', 'Payment exceeding the amount due.'],
  ['finance.credit_note', 'credit note', 'Document reducing the receivable owed by the payer.'],
  ['finance.debit_note', 'debit note', 'Document increasing the receivable owed by the payer.'],
  ['finance.trust_account', 'trust account', 'Segregated account holding funds owed to another party.'],
  ['finance.escrow', 'escrow account', 'Funds held by a third party pending completion of an offtake or transfer.'],
  ['finance.commission', 'broker commission', 'Fee paid to a mineral broker calculated as a percentage of a sale.'],
  ['finance.management_fee', 'management fee', 'Fee for ongoing mine-management or operatorship services.'],
  ['finance.advance', 'production advance', 'Money advanced by an offtaker against future mineral deliveries.'],
  ['finance.streaming', 'metal stream', 'Upfront financing repaid by delivering a fixed share of future metal at a discount.'],
  ['finance.hedging', 'price hedging', 'Locking in a forward metal price to manage commodity-price risk.'],
  ['finance.spot_price', 'spot price', 'The prevailing market price for immediate sale of a metal.'],
  ['finance.lbma_fix', 'LBMA fix', 'London Bullion Market Association reference price used to value gold sales.', ['TZ', 'GH', 'ZA']],
  ['finance.grade_premium', 'grade premium', 'Price uplift for ore or concentrate above a benchmark grade.'],
  ['finance.treatment_charge', 'treatment & refining charge (TC/RC)', 'Smelter charges deducted from concentrate value for processing and refining.'],
  ['finance.moisture_deduction', 'moisture deduction', 'Reduction of concentrate payable weight for contained moisture.'],
  ['finance.assay_split', 'assay-split settlement', 'Final settlement reconciling mine, buyer, and umpire assays of a consignment.'],
  ['finance.payability', 'payable metal percentage', 'The share of contained metal a smelter or refiner pays for after losses.'],
  ['finance.default_interest', 'default interest', 'Interest charged on overdue sums at a contractual rate.'],
  ['finance.retention', 'retention', 'Sum withheld from a contractor pending completion or defects rectification.'],
  ['finance.rehabilitation_provision', 'rehabilitation provision', 'Accounting reserve for the future cost of mine closure and site rehabilitation.'],
  ['finance.depletion', 'depletion charge', 'Amortisation of a mineral reserve as ore is extracted.'],
  ['finance.capital_allowance', 'capital allowance', 'Tax deduction for depreciation of mining plant and equipment.'],
  ['finance.withholding_tax', 'withholding tax', 'Tax withheld at source on payments to subcontractors and non-resident service providers.', ['TZ', 'GH', 'ZA']],
  ['finance.vat', 'VAT', 'Value-added tax levied on supplies of goods and services.'],
  ['finance.corporate_income_tax', 'corporate income tax', 'Tax on the taxable profit of a mining company (30% in Tanzania).', ['TZ']],
  ['finance.aslm', 'alternative minimum tax', 'Minimum tax on unrelieved losses applied to long-loss-making miners.', ['TZ']],
  ['finance.local_govt_levy', 'local government service levy', 'A 0.3% levy on turnover payable to the host district council.', ['TZ']],
  ['finance.fx_settlement', 'FX settlement', 'Conversion and settlement of export proceeds between USD and TZS.', ['TZ']],
  ['finance.tzs_settlement', 'TZS domestic settlement', 'Settlement of domestic mineral sales and obligations in Tanzanian shillings.', ['TZ']],
  ['finance.cost_per_ounce', 'all-in sustaining cost (AISC)', 'Total cost to produce an ounce of gold, including sustaining capital.'],
  ['finance.cut_off_grade', 'cut-off grade economics', 'The lowest ore grade that can be mined and processed at a profit.'],
];

export const FINANCE_ENTRIES: readonly GlossaryEntry[] = Object.freeze([
  ...buildEntries(CORE_SPECS),
  ...enOnlyBatch('finance', ['TZ', 'GH', 'KE'], EXTRA_ROWS),
]);
