/**
 * Mining-rights glossary (licence lifecycle + title/tenure terms).
 *
 * Borjie-era replacement for the legacy pre-Borjie estate `tenancy`
 * file. Where the old corpus held landlord-tenant tenure vocabulary,
 * this file holds the Tanzanian mineral-rights tenure stack: licence
 * classes (PML / ML / SML), grant / renewal / relinquishment, free-
 * carried State interest, beneficiation, and the offtake / clearing
 * obligations that sit on top of a mineral right.
 *
 * The `category` bucket is kept as `'tenancy'` for backward
 * compatibility with the coverage/lookup registry (the GlossaryCategory
 * enum is shared across every category file and the lookup API); read
 * it as "tenure" in the mining sense — the legal relationship between
 * the State, the right-holder, and the ground.
 *
 * Priority Tanzanian-mining locales (sw + en) are curated; the remaining
 * locales fall back to English via `withEnglishOnly`. The general
 * operating-vocabulary file (`./mining.ts`) covers shaft/ore/assay; this
 * file is the rights/tenure layer.
 *
 * Citations refer to real statutes:
 *   - TZ: The Mining Act, 2010 (Cap 123) and the 2017 amendments
 *         (the Written Laws (Miscellaneous Amendments) Act, 2017 and the
 *         Natural Wealth and Resources (Permanent Sovereignty) Act, 2017).
 *   - TZ: The Mining (Mineral Rights) Regulations, 2018.
 *   - TZ: The Mining (Local Content) Regulations, 2018.
 *   - TZ: The Mining (Mineral and Gem Houses) Regulations, 2019.
 */

import { buildEntries, enOnlyBatch, type EntrySpec } from './helpers.js';
import type { GlossaryEntry } from '../types.js';

const CORE_SPECS: readonly EntrySpec[] = [
  {
    id: 'tenancy.mineral_right',
    en: 'mineral right',
    def: 'A statutory authority granted by the State to prospect for, mine, process, or deal in minerals within a defined area for a defined term.',
    cat: 'tenancy',
    juris: ['TZ', 'KE', 'GH', 'ZA', 'AU', 'CD', 'ZM'],
    t: {
      sw: 'haki ya madini',
      ar: 'حق التعدين',
      fr: 'droit minier',
      de: 'Bergrecht',
      ko: '광업권',
      ja: '鉱業権',
      pt: 'direito mineiro',
      es: 'derecho minero',
      zh: '矿业权',
      hi: 'खनिज अधिकार',
    },
    cite: { jurisdiction: 'TZ', statuteRef: 'Mining Act', section: 's.6', year: 2010 },
    syn: ['mineral title'],
    related: ['tenancy.pml', 'tenancy.mining_licence'],
  },
  {
    id: 'tenancy.tenure',
    en: 'mineral tenure',
    def: 'The legal relationship between the State, the right-holder, and the ground, defining how long and on what terms a mineral right may be held.',
    cat: 'tenancy',
    juris: ['TZ', 'KE', 'GH', 'ZA', 'AU'],
    t: {
      sw: 'umiliki wa haki ya madini',
      ar: 'حيازة معدنية',
      fr: 'tenure minière',
      de: 'Bergbauberechtigung',
      ko: '광업 보유권',
      ja: '鉱業保有権',
      pt: 'posse mineira',
      es: 'tenencia minera',
      zh: '矿权保有',
      hi: 'खनिज धारिता',
    },
  },
  {
    id: 'tenancy.state',
    en: 'the State (mineral owner)',
    def: 'In Tanzania all minerals are vested in the United Republic; the State grants mineral rights but retains permanent sovereignty over the resource.',
    cat: 'tenancy',
    juris: ['TZ', 'GH', 'ZA', 'ZM', 'CD'],
    t: {
      sw: 'Serikali (mmiliki wa madini)',
      ar: 'الدولة (مالك المعادن)',
      fr: "l'État (propriétaire minéral)",
      de: 'der Staat (Mineraleigentümer)',
      ko: '국가 (광물 소유자)',
      ja: '国家（鉱物所有者）',
      pt: 'o Estado (proprietário mineral)',
      es: 'el Estado (propietario mineral)',
      zh: '国家（矿产所有者）',
      hi: 'राज्य (खनिज स्वामी)',
    },
    cite: { jurisdiction: 'TZ', statuteRef: 'Permanent Sovereignty Act', section: 's.4', year: 2017 },
  },
  {
    id: 'tenancy.right_holder',
    en: 'right-holder',
    def: 'The licensed person or company in whom a mineral right is vested; bears the royalty, reporting, and local-content obligations attached to it.',
    cat: 'tenancy',
    juris: ['TZ', 'KE', 'GH', 'ZA', 'AU'],
    t: {
      sw: 'mwenye haki ya madini',
      ar: 'صاحب الحق المعدني',
      fr: 'titulaire du droit minier',
      de: 'Rechtsinhaber',
      ko: '광업권자',
      ja: '鉱業権者',
      pt: 'titular do direito',
      es: 'titular del derecho',
      zh: '矿权持有人',
      hi: 'अधिकार धारक',
    },
  },
  {
    id: 'tenancy.pml',
    en: 'Primary Mining Licence (PML)',
    def: 'Citizen-only mineral right for artisanal and small-scale mining over a small area, valid for seven years and renewable; not grantable to a foreign-controlled company.',
    cat: 'tenancy',
    juris: ['TZ'],
    t: {
      sw: 'Leseni ya Msingi ya Uchimbaji (PML)',
      ar: 'رخصة التعدين الأولية',
      fr: 'permis minier primaire (PML)',
      de: 'primäre Bergbaulizenz (PML)',
      ko: '1차 광업 면허 (PML)',
      ja: '一次採掘ライセンス (PML)',
      pt: 'licença mineira primária (PML)',
      es: 'licencia minera primaria (PML)',
      zh: '初级采矿许可证 (PML)',
      hi: 'प्राथमिक खनन लाइसेंस (PML)',
    },
    cite: { jurisdiction: 'TZ', statuteRef: 'Mining Act', section: 's.8', year: 2010 },
    notes: 'Reserved for Tanzanian citizens; issued by the Mining Commission; seven-year term, renewable.',
    syn: ['PML'],
    related: ['tenancy.mining_licence', 'tenancy.special_mining_licence'],
  },
  {
    id: 'tenancy.mining_licence',
    en: 'Mining Licence (ML)',
    def: 'Mid-tier mineral right for medium-scale mining where the capital investment is below the special-mining-licence threshold; up to ten years and renewable.',
    cat: 'tenancy',
    juris: ['TZ'],
    t: {
      sw: 'Leseni ya Uchimbaji (ML)',
      ar: 'رخصة التعدين',
      fr: "licence d'exploitation minière (ML)",
      de: 'Bergbaulizenz (ML)',
      ko: '광업 면허 (ML)',
      ja: '採掘ライセンス (ML)',
      pt: 'licença de mineração (ML)',
      es: 'licencia de minería (ML)',
      zh: '采矿许可证 (ML)',
      hi: 'खनन लाइसेंस (ML)',
    },
    cite: { jurisdiction: 'TZ', statuteRef: 'Mining Act', section: 's.40', year: 2010 },
    syn: ['ML'],
  },
  {
    id: 'tenancy.special_mining_licence',
    en: 'Special Mining Licence (SML)',
    def: 'Large-scale mineral right for capital-intensive operations above the prescribed investment threshold; subject to the 16% State free-carried interest and a mineral-development agreement.',
    cat: 'tenancy',
    juris: ['TZ'],
    t: {
      sw: 'Leseni Maalum ya Uchimbaji (SML)',
      ar: 'رخصة التعدين الخاصة',
      fr: "licence d'exploitation minière spéciale (SML)",
      de: 'spezielle Bergbaulizenz (SML)',
      ko: '특별 광업 면허 (SML)',
      ja: '特別採掘ライセンス (SML)',
      pt: 'licença especial de mineração (SML)',
      es: 'licencia especial de minería (SML)',
      zh: '特别采矿许可证 (SML)',
      hi: 'विशेष खनन लाइसेंस (SML)',
    },
    cite: { jurisdiction: 'TZ', statuteRef: 'Mining Act', section: 's.41', year: 2010 },
    notes: 'Carries the 16% non-dilutable free-carried State interest under the 2017 amendments.',
    syn: ['SML'],
    related: ['tenancy.free_carried_interest'],
  },
  {
    id: 'tenancy.prospecting_licence',
    en: 'Prospecting Licence (PL)',
    def: 'Exploration-stage mineral right authorising the holder to search for and delineate a mineral deposit before applying for a mining licence.',
    cat: 'tenancy',
    juris: ['TZ', 'GH', 'ZA', 'AU'],
    t: {
      sw: 'Leseni ya Utafiti wa Madini (PL)',
      ar: 'رخصة التنقيب',
      fr: 'permis de prospection (PL)',
      de: 'Schürferlaubnis (PL)',
      ko: '탐사 면허 (PL)',
      ja: '探鉱ライセンス (PL)',
      pt: 'licença de prospecção (PL)',
      es: 'licencia de prospección (PL)',
      zh: '勘探许可证 (PL)',
      hi: 'पूर्वेक्षण लाइसेंस (PL)',
    },
    cite: { jurisdiction: 'TZ', statuteRef: 'Mining Act', section: 's.29', year: 2010 },
    syn: ['PL'],
  },
  {
    id: 'tenancy.grant',
    en: 'grant of mineral right',
    def: 'The act by which the Mining Commission confers a mineral right on an applicant who meets the statutory and local-content requirements.',
    cat: 'tenancy',
    juris: ['TZ', 'KE', 'GH', 'ZA'],
    t: {
      sw: 'utoaji wa haki ya madini',
      ar: 'منح الحق المعدني',
      fr: 'octroi du droit minier',
      de: 'Verleihung des Bergrechts',
      ko: '광업권 부여',
      ja: '鉱業権の付与',
      pt: 'concessão do direito mineiro',
      es: 'otorgamiento del derecho minero',
      zh: '矿权授予',
      hi: 'खनिज अधिकार अनुदान',
    },
  },
  {
    id: 'tenancy.relinquishment',
    en: 'relinquishment',
    def: 'The surrender by the holder of all or part of a licence area, typically a portion of the exploration ground at each renewal.',
    cat: 'tenancy',
    juris: ['TZ', 'GH', 'ZA', 'AU'],
    t: {
      sw: 'kuachia eneo la leseni',
      ar: 'التنازل عن منطقة الترخيص',
      fr: 'abandon de superficie',
      de: 'Flächenrückgabe',
      ko: '광구 반납',
      ja: '鉱区の放棄',
      pt: 'renúncia de área',
      es: 'renuncia de área',
      zh: '区块放弃',
      hi: 'क्षेत्र अध्यर्पण',
    },
  },
  {
    id: 'tenancy.revocation',
    en: 'revocation',
    def: "The Mining Commission's cancellation of a mineral right for breach of its conditions, non-payment of royalty or rent, or failure to develop.",
    cat: 'tenancy',
    juris: ['TZ', 'GH', 'ZA'],
    t: {
      sw: 'kufutwa kwa leseni',
      ar: 'إلغاء الحق المعدني',
      fr: 'révocation du droit minier',
      de: 'Widerruf des Bergrechts',
      ko: '광업권 취소',
      ja: '鉱業権の取消',
      pt: 'revogação do direito mineiro',
      es: 'revocación del derecho minero',
      zh: '矿权吊销',
      hi: 'खनिज अधिकार निरस्तीकरण',
    },
    cite: { jurisdiction: 'TZ', statuteRef: 'Mining Act', section: 's.51', year: 2010 },
  },
  {
    id: 'tenancy.licence_renewal',
    en: 'licence renewal',
    def: 'Statutory extension of a mineral right beyond its initial term, conditional on compliance, minimum work, and up-to-date royalty and annual-rent payment.',
    cat: 'tenancy',
    juris: ['TZ', 'KE', 'GH', 'ZA'],
    t: {
      sw: 'kuongezwa kwa leseni',
      ar: 'تجديد الترخيص',
      fr: 'renouvellement du permis',
      de: 'Lizenzverlängerung',
      ko: '면허 갱신',
      ja: 'ライセンス更新',
      pt: 'renovação da licença',
      es: 'renovación de la licencia',
      zh: '许可证续期',
      hi: 'लाइसेंस नवीकरण',
    },
    cite: { jurisdiction: 'TZ', statuteRef: 'Mining Act', section: 's.43', year: 2010 },
  },
  {
    id: 'tenancy.annual_rent',
    en: 'annual mineral-right rent',
    def: 'Per-hectare ground rent payable each year to keep a mineral right in good standing, distinct from royalty on production.',
    cat: 'tenancy',
    juris: ['TZ', 'GH', 'ZA'],
    t: {
      sw: 'kodi ya mwaka ya eneo la madini',
      ar: 'الإيجار السنوي للحق المعدني',
      fr: 'redevance superficiaire annuelle',
      de: 'jährliche Feldesabgabe',
      ko: '연간 광구세',
      ja: '年間鉱区使用料',
      pt: 'taxa anual de superfície',
      es: 'canon anual de superficie',
      zh: '年度矿区使用费',
      hi: 'वार्षिक क्षेत्र किराया',
    },
  },
  {
    id: 'tenancy.cadastre',
    en: 'mining cadastre',
    def: 'The official register and map of all mineral-right areas, administered so that no two live rights overlap the same ground.',
    cat: 'tenancy',
    juris: ['TZ', 'GH', 'ZA', 'AU', 'CD'],
    t: {
      sw: 'daftari la maeneo ya madini',
      ar: 'سجل المساحة التعدينية',
      fr: 'cadastre minier',
      de: 'Bergbaukataster',
      ko: '광업 지적',
      ja: '鉱業登録簿',
      pt: 'cadastro mineiro',
      es: 'catastro minero',
      zh: '矿业地籍',
      hi: 'खनन कैडस्ट्रे',
    },
  },
  {
    id: 'tenancy.free_carried_interest',
    en: 'free-carried interest',
    def: "The State's 16% non-dilutable equity in special-mining-licence operations, acquired at no cost under the 2017 amendments, with a right to acquire up to a further share.",
    cat: 'tenancy',
    juris: ['TZ'],
    t: {
      sw: 'hisa za bure za Serikali',
      ar: 'حصة محمولة مجانية',
      fr: 'participation libre portée',
      de: 'kostenfreie Beteiligung',
      ko: '무상 보유 지분',
      ja: '無償キャリー持分',
      pt: 'participação livre transportada',
      es: 'participación libre transportada',
      zh: '免费持有权益',
      hi: 'निःशुल्क वहित हिस्सेदारी',
    },
    cite: { jurisdiction: 'TZ', statuteRef: 'Mining Act', section: 's.10', year: 2017 },
    notes: '16% free-carried interest is mandatory for SML holders; the State may acquire up to 50% in proportion to tax expenditures.',
  },
  {
    id: 'tenancy.mineral_development_agreement',
    en: 'mineral development agreement (MDA)',
    def: 'A negotiated agreement between the State and a large-scale right-holder governing fiscal terms, local content, and development obligations; renegotiable under the 2017 sovereignty laws.',
    cat: 'tenancy',
    juris: ['TZ'],
    t: {
      sw: 'mkataba wa maendeleo ya madini (MDA)',
      ar: 'اتفاقية تطوير المعادن',
      fr: 'accord de développement minier (MDA)',
      de: 'Mineralentwicklungsvertrag (MDA)',
      ko: '광물 개발 협정 (MDA)',
      ja: '鉱物開発協定 (MDA)',
      pt: 'acordo de desenvolvimento mineral (MDA)',
      es: 'acuerdo de desarrollo mineral (MDA)',
      zh: '矿产开发协议 (MDA)',
      hi: 'खनिज विकास समझौता (MDA)',
    },
    cite: { jurisdiction: 'TZ', statuteRef: 'Permanent Sovereignty Act', section: 's.6', year: 2017 },
    syn: ['MDA'],
  },
  {
    id: 'tenancy.local_content',
    en: 'local content',
    def: 'The statutory requirement that mining operations use Tanzanian goods, services, employment, and shareholding to a prescribed minimum proportion.',
    cat: 'tenancy',
    juris: ['TZ', 'GH', 'NG'],
    t: {
      sw: 'maudhui ya ndani',
      ar: 'المحتوى المحلي',
      fr: 'contenu local',
      de: 'lokaler Wertschöpfungsanteil',
      ko: '현지 조달 비율',
      ja: 'ローカルコンテンツ',
      pt: 'conteúdo local',
      es: 'contenido local',
      zh: '本地含量',
      hi: 'स्थानीय सामग्री',
    },
    cite: { jurisdiction: 'TZ', statuteRef: 'Local Content Regulations', section: 'reg.4', year: 2018 },
  },
  {
    id: 'tenancy.offtake_agreement',
    en: 'offtake agreement',
    def: 'A forward contract under which a buyer commits to purchase a defined quantity and grade of mineral output, often before production begins.',
    cat: 'tenancy',
    juris: ['TZ', 'KE', 'GH', 'ZA', 'AU', 'CD', 'ZM'],
    t: {
      sw: 'mkataba wa ununuzi wa madini',
      ar: 'اتفاقية الشراء',
      fr: "contrat d'enlèvement",
      de: 'Abnahmevertrag',
      ko: '인수 계약',
      ja: 'オフテイク契約',
      pt: 'contrato de aquisição',
      es: 'contrato de compraventa (offtake)',
      zh: '包销协议',
      hi: 'ऑफटेक अनुबंध',
    },
    syn: ['offtake'],
    related: ['tenancy.clearing_fee'],
  },
  {
    id: 'tenancy.beneficiation',
    en: 'beneficiation',
    def: 'In-country processing of ore into a higher-value product (concentrate, doré, refined metal) before export, encouraged or required by Tanzanian policy.',
    cat: 'tenancy',
    juris: ['TZ', 'ZA', 'GH'],
    t: {
      sw: 'uchakataji wa madini ndani ya nchi',
      ar: 'المعالجة المعدنية',
      fr: 'valorisation du minerai',
      de: 'Veredelung',
      ko: '선광·정련',
      ja: '選鉱処理',
      pt: 'beneficiamento',
      es: 'beneficio del mineral',
      zh: '选矿增值',
      hi: 'लाभकारीकरण',
    },
  },
  {
    id: 'tenancy.export_permit',
    en: 'mineral export permit',
    def: 'A permit from the Mining Commission authorising a specific consignment of minerals to leave the country after assay, valuation, and clearing.',
    cat: 'tenancy',
    juris: ['TZ', 'GH'],
    t: {
      sw: 'kibali cha kusafirisha madini nje',
      ar: 'تصريح تصدير المعادن',
      fr: "permis d'exportation de minéraux",
      de: 'Mineralexportgenehmigung',
      ko: '광물 수출 허가',
      ja: '鉱物輸出許可',
      pt: 'autorização de exportação mineral',
      es: 'permiso de exportación mineral',
      zh: '矿产出口许可',
      hi: 'खनिज निर्यात परमिट',
    },
    cite: { jurisdiction: 'TZ', statuteRef: 'Mining Act', section: 's.59', year: 2010 },
  },
  {
    id: 'tenancy.mineral_rights_register',
    en: 'mineral-rights register',
    def: 'The public record of every granted, renewed, transferred, or revoked mineral right, maintained by the Mining Commission.',
    cat: 'tenancy',
    juris: ['TZ', 'GH', 'ZA'],
    t: {
      sw: 'daftari la haki za madini',
      ar: 'سجل الحقوق المعدنية',
      fr: 'registre des droits miniers',
      de: 'Bergrechtsregister',
      ko: '광업권 등록부',
      ja: '鉱業権登録簿',
      pt: 'registo de direitos mineiros',
      es: 'registro de derechos mineros',
      zh: '矿业权登记册',
      hi: 'खनिज अधिकार रजिस्टर',
    },
  },
  {
    id: 'tenancy.transfer_of_right',
    en: 'transfer of mineral right',
    def: 'Assignment of a mineral right to another qualified party, valid only with the prior written approval of the Minister or Mining Commission.',
    cat: 'tenancy',
    juris: ['TZ', 'GH', 'ZA'],
    t: {
      sw: 'uhamisho wa haki ya madini',
      ar: 'نقل الحق المعدني',
      fr: 'cession du droit minier',
      de: 'Übertragung des Bergrechts',
      ko: '광업권 양도',
      ja: '鉱業権の譲渡',
      pt: 'transferência do direito mineiro',
      es: 'transferencia del derecho minero',
      zh: '矿权转让',
      hi: 'खनिज अधिकार हस्तांतरण',
    },
    cite: { jurisdiction: 'TZ', statuteRef: 'Mining Act', section: 's.8A', year: 2017 },
  },
  {
    id: 'tenancy.surface_rights',
    en: 'surface rights',
    def: 'Rights of access to and use of the land surface above a mineral right, requiring compensation to lawful occupiers before disturbance.',
    cat: 'tenancy',
    juris: ['TZ', 'KE', 'GH', 'ZA'],
    t: {
      sw: 'haki za uso wa ardhi',
      ar: 'حقوق السطح',
      fr: 'droits de surface',
      de: 'Oberflächenrechte',
      ko: '지표권',
      ja: '地表権',
      pt: 'direitos de superfície',
      es: 'derechos de superficie',
      zh: '地表权',
      hi: 'सतही अधिकार',
    },
    cite: { jurisdiction: 'TZ', statuteRef: 'Mining Act', section: 's.95', year: 2010 },
  },
  {
    id: 'tenancy.compensation',
    en: 'compensation to occupiers',
    def: 'Payment due to a landholder or community lawfully occupying ground that a right-holder needs to disturb, assessed before operations begin.',
    cat: 'tenancy',
    juris: ['TZ', 'KE', 'GH', 'ZA'],
    t: {
      sw: 'fidia kwa wakaaji',
      ar: 'تعويض الشاغلين',
      fr: 'indemnisation des occupants',
      de: 'Entschädigung der Nutzer',
      ko: '점유자 보상',
      ja: '占有者への補償',
      pt: 'indemnização aos ocupantes',
      es: 'indemnización a los ocupantes',
      zh: '占用者补偿',
      hi: 'अधिभोगियों को मुआवजा',
    },
  },
  {
    id: 'tenancy.community_development_agreement',
    en: 'community development agreement',
    def: 'A binding plan, required of larger operations, setting out how the mine will share benefits with and develop its host community.',
    cat: 'tenancy',
    juris: ['TZ', 'GH'],
    t: {
      sw: 'mkataba wa maendeleo ya jamii',
      ar: 'اتفاقية تنمية المجتمع',
      fr: 'accord de développement communautaire',
      de: 'Gemeindeentwicklungsvertrag',
      ko: '지역사회 개발 협정',
      ja: '地域開発協定',
      pt: 'acordo de desenvolvimento comunitário',
      es: 'acuerdo de desarrollo comunitario',
      zh: '社区发展协议',
      hi: 'समुदाय विकास समझौता',
    },
  },
  {
    id: 'tenancy.dealer_licence',
    en: "mineral dealer's licence",
    def: 'A licence authorising the holder to buy and sell minerals from licensed producers; a prerequisite for lawful mineral trading.',
    cat: 'tenancy',
    juris: ['TZ', 'GH'],
    t: {
      sw: 'leseni ya mfanyabiashara wa madini',
      ar: 'رخصة تاجر المعادن',
      fr: 'licence de négociant en minéraux',
      de: 'Mineralhändlerlizenz',
      ko: '광물 거래 면허',
      ja: '鉱物取引業ライセンス',
      pt: 'licença de comerciante de minerais',
      es: 'licencia de comerciante de minerales',
      zh: '矿产经销商许可证',
      hi: 'खनिज व्यापारी लाइसेंस',
    },
    cite: { jurisdiction: 'TZ', statuteRef: 'Mining Act', section: 's.82', year: 2010 },
  },
  {
    id: 'tenancy.broker_licence',
    en: "mineral broker's licence",
    def: 'A licence permitting the holder to broker the sale of minerals between artisanal producers and dealers within a designated area.',
    cat: 'tenancy',
    juris: ['TZ'],
    t: {
      sw: 'leseni ya dalali wa madini',
      ar: 'رخصة وسيط المعادن',
      fr: 'licence de courtier en minéraux',
      de: 'Mineralmaklerlizenz',
      ko: '광물 중개 면허',
      ja: '鉱物仲介ライセンス',
      pt: 'licença de corretor de minerais',
      es: 'licencia de corredor de minerales',
      zh: '矿产经纪人许可证',
      hi: 'खनिज दलाल लाइसेंस',
    },
  },
  {
    id: 'tenancy.mineral_and_gem_house',
    en: 'mineral and gem house',
    def: 'A government-designated trading hub where licensed dealers buy, value, and tax minerals close to the point of production.',
    cat: 'tenancy',
    juris: ['TZ'],
    t: {
      sw: 'soko la madini na vito',
      ar: 'دار المعادن والأحجار الكريمة',
      fr: 'maison des minéraux et gemmes',
      de: 'Mineralien- und Edelsteinhaus',
      ko: '광물·보석 거래소',
      ja: '鉱物・宝石取引所',
      pt: 'casa de minerais e gemas',
      es: 'casa de minerales y gemas',
      zh: '矿产宝石交易中心',
      hi: 'खनिज एवं रत्न गृह',
    },
    cite: { jurisdiction: 'TZ', statuteRef: 'Mineral and Gem Houses Regulations', section: 'reg.3', year: 2019 },
    notes: 'Regional mineral markets (e.g. Geita, Mwanza, Mererani) where output is sold, assayed, and royalty/clearing applied.',
  },
];

const EXTRA_ROWS: ReadonlyArray<
  readonly [string, string, string, ReadonlyArray<string>?]
> = [
  // --- Licence lifecycle / administration ---
  ['tenancy.application', 'mineral-right application', 'Formal request to the Mining Commission for the grant of a mineral right.', ['TZ', 'GH', 'ZA']],
  ['tenancy.area_demarcation', 'area demarcation', 'Survey and beaconing of a licence boundary on the ground.', ['TZ', 'GH', 'ZA']],
  ['tenancy.beacon', 'boundary beacon', 'A physical marker fixing a corner of a licensed mineral-right area.', ['TZ', 'GH']],
  ['tenancy.coordinates', 'cadastral coordinates', 'The geo-referenced corner points defining a licence block.', ['TZ', 'GH', 'AU']],
  ['tenancy.work_obligation', 'minimum work obligation', 'The minimum exploration or development spend a holder must incur each period to retain a right.', ['TZ', 'GH', 'ZA', 'AU']],
  ['tenancy.expenditure_report', 'expenditure report', 'Statement of money spent on a licence area, filed to evidence the work obligation.', ['TZ', 'GH', 'AU']],
  ['tenancy.holding_in_good_standing', 'good standing', 'Status of a right that is current on rent, royalty, and reporting and therefore not liable to revocation.', ['TZ', 'GH', 'ZA']],
  ['tenancy.lapse', 'lapse of right', 'Automatic expiry of a mineral right at the end of its term where renewal is not granted.', ['TZ', 'GH', 'ZA']],
  ['tenancy.suspension', 'suspension of operations', 'A temporary, approved halt of mining without surrendering the right.', ['TZ', 'GH', 'ZA']],
  ['tenancy.amalgamation', 'amalgamation of licences', 'Combining adjoining mineral rights of the same class into a single right.', ['TZ', 'GH']],
  ['tenancy.subdivision', 'subdivision of a licence', 'Splitting a mineral-right area into smaller blocks.', ['TZ', 'GH']],
  ['tenancy.priority', 'priority of application', 'The first-come rule deciding competing applications over the same ground.', ['TZ', 'GH', 'AU']],
  ['tenancy.overlapping_claim', 'overlapping claim', 'A dispute where two applicants or holders assert rights over the same ground.', ['TZ', 'GH', 'ZA']],
  ['tenancy.encroachment', 'encroachment', 'Mining beyond the lawful boundary of a licensed area.', ['TZ', 'GH', 'ZA']],
  // --- Title / tenure variants ---
  ['tenancy.gemstone_right', 'gemstone mining right', 'A mineral right specific to coloured gemstones such as tanzanite or ruby.', ['TZ']],
  ['tenancy.tanzanite_block', 'Mererani tanzanite block', 'A demarcated mining block within the controlled Mererani tanzanite area.', ['TZ']],
  ['tenancy.controlled_area', 'controlled mining area', 'A statutorily fenced and access-controlled zone (e.g. Mererani) with extra trade and security rules.', ['TZ']],
  ['tenancy.reserved_area', 'reserved area', 'Ground withdrawn from licensing and held by the State for strategic or competitive-tender allocation.', ['TZ', 'GH', 'ZA']],
  ['tenancy.designated_zone', 'designated artisanal zone', 'An area set aside for citizen artisanal miners under PMLs.', ['TZ']],
  ['tenancy.restricted_mineral', 'restricted/strategic mineral', 'A mineral (e.g. uranium, helium) whose dealing is restricted under special rules.', ['TZ']],
  // --- Royalty / fiscal terms (tenure-attached) ---
  ['tenancy.royalty_metallic', 'royalty (metallic minerals)', 'The 6% royalty on the gross value of gold, copper, and other metallic minerals.', ['TZ']],
  ['tenancy.royalty_gemstone', 'royalty (gemstones)', 'The 6% royalty on the gross value of diamonds and coloured gemstones.', ['TZ']],
  ['tenancy.clearing_fee', 'clearing fee', 'A 1% inspection/clearing charge on the value of minerals at the point of sale or export, additional to royalty.', ['TZ']],
  ['tenancy.gross_value', 'gross value', 'The market value of minerals at the point of refining or sale, used as the royalty base.', ['TZ', 'GH', 'ZA']],
  ['tenancy.valuation', 'mineral valuation', 'Government assay-based assessment of a consignment to set the royalty and clearing charge.', ['TZ', 'GH']],
  ['tenancy.inspection_fee', 'inspection fee', 'Charge for the official examination and weighing of a mineral consignment.', ['TZ']],
  ['tenancy.tra_assessment', 'TRA assessment', 'Tanzania Revenue Authority assessment of corporate income tax and withholding on mining income.', ['TZ']],
  ['tenancy.withholding_tax', 'withholding tax (mining services)', 'Tax withheld at source on payments to subcontractors and non-resident service providers.', ['TZ']],
  ['tenancy.capital_gains', 'capital gains on right transfer', 'Tax arising on the change of control or transfer of a mineral right.', ['TZ']],
  // --- Compliance / sovereignty stack ---
  ['tenancy.permanent_sovereignty', 'permanent sovereignty', "The 2017-law principle that natural wealth is held in trust for the people and cannot be alienated.", ['TZ']],
  ['tenancy.no_export_unprocessed', 'ban on export of unprocessed ore', 'The policy restricting export of raw/unprocessed ore to push in-country beneficiation.', ['TZ']],
  ['tenancy.beneficiation_obligation', 'beneficiation obligation', 'A licence condition to process ore domestically to a defined level before export.', ['TZ']],
  ['tenancy.local_shareholding', 'indigenous shareholding', 'The minimum equity that Tanzanian citizens or entities must hold in a mining company.', ['TZ']],
  ['tenancy.local_employment', 'local-employment quota', 'The proportion of jobs that must go to Tanzanian nationals at each grade.', ['TZ', 'GH', 'NG']],
  ['tenancy.local_procurement', 'local-procurement plan', 'A filed plan committing the operation to source goods and services from Tanzanian suppliers.', ['TZ', 'GH', 'NG']],
  ['tenancy.mining_commission_approval', 'Mining Commission approval', 'The administrative consent required for grants, transfers, renewals, and exports.', ['TZ']],
  ['tenancy.gmp', 'good mining practice', 'The standard of safe, efficient, and environmentally sound operation expected of a right-holder.', ['TZ', 'GH', 'ZA', 'AU']],
  ['tenancy.mine_closure_plan', 'mine closure plan', 'An approved plan for safe decommissioning and rehabilitation at the end of mine life.', ['TZ', 'GH', 'ZA', 'AU']],
  ['tenancy.rehabilitation_bond', 'rehabilitation bond', 'A financial guarantee posted to fund site rehabilitation if the operator defaults.', ['TZ', 'GH', 'ZA', 'AU']],
  ['tenancy.environmental_certificate', 'environmental certificate (EIA)', 'NEMC-issued certificate confirming an approved environmental impact assessment before mining.', ['TZ']],
  // --- 3T / traceability / ASM formalisation ---
  ['tenancy.traceability_3t', '3T traceability', 'Chain-of-custody tracking for tin, tantalum, and tungsten to certify conflict-free origin.', ['TZ', 'CD', 'RW']],
  ['tenancy.conflict_free', 'conflict-free certification', 'Certification that minerals did not finance armed conflict (OECD due-diligence, ICGLR/RCM).', ['TZ', 'CD', 'RW']],
  ['tenancy.due_diligence', 'supply-chain due diligence', 'The OECD five-step process for responsible mineral sourcing.', ['TZ', 'CD', 'RW']],
  ['tenancy.asm_formalisation', 'ASM formalisation', 'Bringing artisanal and small-scale miners into the licensed, taxed, and regulated economy.', ['TZ', 'GH']],
  ['tenancy.mercury_free', 'mercury-free processing', 'Gold recovery without mercury, e.g. by gravity or borax, per the Minamata Convention.', ['TZ', 'GH']],
  ['tenancy.minamata', 'Minamata Convention', 'The international treaty phasing down mercury use in artisanal gold mining.', ['TZ', 'GH']],
  ['tenancy.cooperative', 'miners cooperative (chama)', 'A registered group of artisanal miners pooling a PML, equipment, and proceeds.', ['TZ']],
  // --- Output / trade lifecycle ---
  ['tenancy.dore', 'doré bar', 'A semi-pure alloy bar of gold and silver produced on site before refining.', ['TZ', 'GH', 'ZA']],
  ['tenancy.concentrate', 'concentrate', 'An upgraded mineral product after gangue removal, sold by contained-metal grade.', ['TZ', 'ZA', 'ZM', 'CD']],
  ['tenancy.lot', 'sale lot', 'A weighed, assayed, and tagged parcel of mineral offered for sale.', ['TZ', 'GH']],
  ['tenancy.lbma_fix', 'LBMA fix', 'The London Bullion Market Association reference price used to value gold sales.', ['TZ', 'GH', 'ZA']],
  ['tenancy.spot_sale', 'spot sale', 'Sale of a consignment at the prevailing market price, as opposed to a forward offtake.', ['TZ', 'GH']],
  ['tenancy.consignment', 'consignment', 'A discrete shipment of minerals moving from mine to buyer or export.', ['TZ', 'GH']],
  ['tenancy.bullion', 'bullion', 'Refined precious metal in bar or ingot form.', ['TZ', 'GH', 'ZA']],
];

export const MINING_RIGHTS_ENTRIES: readonly GlossaryEntry[] = Object.freeze([
  ...buildEntries(CORE_SPECS),
  ...enOnlyBatch('tenancy', ['TZ', 'GH', 'KE'], EXTRA_ROWS),
]);
