/**
 * compile.ts — Deterministic compiler from a validated ModuleSpec to
 * (a) safe Drizzle-compatible migration SQL and (b) serialised Zod
 * validators.
 *
 * Design contract:
 *
 *   1. Pure: same input ALWAYS produces same output (no Date.now(),
 *      no random ids, no env reads). Enables caching the compile
 *      result by hash of (tenantId + spec).
 *
 *   2. Safe: every identifier emitted into SQL is either:
 *        - A constant string we control (table prefix, column type)
 *        - A slug that already passed Zod regex `^[a-z][a-z0-9_]{0,47}$`
 *      Therefore the output cannot host SQL injection.
 *
 *   3. Tenant-scoped at the schema level. Each entity table is named
 *      `tenant_mod_{tenantId}_{entitySlug}` (the canonical tenant-module
 *      namespace the ddl-guard enforces) and includes its own
 *      `tenant_id` and `module_id` columns. The compiler does NOT emit a
 *      table for entities it determines should be backed by `core_entity`
 *      (in v1 — every entity gets a dedicated extension table; the
 *      routing through core_entity for the polymorphic root happens at
 *      the orchestrator layer when it inserts the matching `core_entity`
 *      row).
 *
 *   4. RLS is NOT the compiler's job. The compiler emits ONLY the header
 *      comment, conforming `CREATE TABLE IF NOT EXISTS` statements, and
 *      `CREATE INDEX IF NOT EXISTS` statements. The orchestrator's
 *      ddl-guard auto-injects the canonical FORCE-RLS block from the
 *      returned `tableNames` and rejects any DDL whose tables are not
 *      all covered — the module author can never control RLS.
 *
 *   5. Idempotent. Every emitted statement uses `IF NOT EXISTS`.
 *
 *   6. Identifier-length safe. Postgres silently truncates identifiers
 *      at NAMEDATALEN-1 (63 bytes), which would let two distinct logical
 *      tables collide into one physical table. The compiler refuses to
 *      emit any table or index identifier over the limit.
 *
 *   7. No money mutation. The compiler refuses to back any money
 *      column with an actual table column — it emits a
 *      `MONEY_FIELDS_VIA_LEDGER` comment instead, forcing the
 *      handler code to route through `LedgerService.post()`.
 */

import {
  type ModuleSpec,
  type FieldDecl,
  type CompileResult,
  type ZodValidatorTree,
  type ZodFieldTree,
  SLUG_REGEX,
} from './types.js';
import { exceedsPgIdentifierLimit, PG_IDENTIFIER_MAX_BYTES } from './identifier-limit.js';
import { validateSpec } from './validate.js';

/**
 * Compile a spec for tenant {tenantId} into migration SQL + Zod
 * validators. Throws if the spec is grammatically invalid (caller
 * should validateSpec first to surface errors gracefully).
 */
export function compileSpec(
  spec: ModuleSpec,
  tenantId: string,
): CompileResult {
  if (!isValidTenantSlug(tenantId)) {
    return compileFailure([`unsafe tenantId: ${tenantId}`]);
  }

  // Re-validate the spec — defence in depth. A caller that hands us
  // an unvalidated spec gets a structured error, never raw SQL.
  const v = validateSpec(spec);
  if (!v.ok || !v.spec) {
    return compileFailure(v.errors);
  }

  const sqlParts: string[] = [buildHeaderComment(tenantId)];
  const zodValidators: Record<string, ZodValidatorTree> = {};
  const tableNames: string[] = [];
  const identifierErrors: string[] = [];

  for (const entity of v.spec.entities) {
    const built = buildEntityTableSql(entity, tenantId);
    identifierErrors.push(...built.identifierErrors);
    sqlParts.push(built.sql);
    tableNames.push(built.tableName);
    zodValidators[entity.slug] = buildZodValidatorTree(entity);
  }

  if (identifierErrors.length > 0) {
    return compileFailure(identifierErrors);
  }

  sqlParts.push(buildWorkflowSeed(v.spec, tenantId));

  const uiLayout = buildUiLayout(v.spec);

  return {
    ok: true,
    migrationSql: sqlParts.join('\n\n'),
    tableNames: Object.freeze([...tableNames]),
    zodValidators: Object.freeze(zodValidators),
    uiLayout,
    errors: [],
  };
}

function compileFailure(errors: readonly string[]): CompileResult {
  return {
    ok: false,
    migrationSql: '',
    tableNames: Object.freeze([]),
    zodValidators: {},
    uiLayout: { sections: [] },
    errors: Object.freeze([...errors]),
  };
}

// ─────────────────────────────────────────────────────────────────────
// Building blocks
// ─────────────────────────────────────────────────────────────────────

function buildHeaderComment(tenantId: string): string {
  return [
    `-- ============================================================================`,
    `-- Generated by @borjie/module-spec-engine.`,
    `-- tenant_id: ${tenantId}`,
    `-- Generator version: 0.2.0`,
    `--`,
    `-- Every table created here:`,
    `--   * lives in the public schema with the canonical tenant-module`,
    `--     namespace prefix tenant_mod_${tenantId}_`,
    `--   * carries tenant_id + module_id as the first two columns`,
    `--`,
    `-- Row-security is NOT emitted by the compiler. The orchestrator's`,
    `-- ddl-guard auto-injects the canonical tenant-isolation block (bound`,
    `-- to the app.current_tenant_id GUC) and rejects any DDL whose tables`,
    `-- are not all covered. A module author can never control it.`,
    `--`,
    `-- Money fields are NEVER stored as columns. The compiler emits a`,
    `-- comment marker only — the module handler routes money through`,
    `-- LedgerService.post() per the master invariant.`,
    `-- ============================================================================`,
  ].join('\n');
}

interface BuiltEntityTable {
  readonly sql: string;
  readonly tableName: string;
  readonly identifierErrors: readonly string[];
}

function buildEntityTableSql(
  entity: ReturnType<typeof spec_entity>,
  tenantId: string,
): BuiltEntityTable {
  const tableName = entityTableName(tenantId, entity.slug);

  // Columns common to every module entity table.
  const columns: string[] = [
    `id                  TEXT PRIMARY KEY`,
    `tenant_id           TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE`,
    `module_id           TEXT NOT NULL REFERENCES modules(id) ON DELETE CASCADE`,
    `display_name        TEXT NOT NULL`,
    `lifecycle_state     TEXT NOT NULL DEFAULT 'active'`,
    `created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()`,
    `updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()`,
    `deleted_at          TIMESTAMPTZ`,
  ];

  const moneyMarkers: string[] = [];

  for (const f of entity.fields) {
    if (f.kind === 'money') {
      // Money is NEVER a column. Emit a marker comment.
      moneyMarkers.push(
        `-- money field '${f.name}' on '${entity.slug}' routes via LedgerService.post() — no column emitted`,
      );
      continue;
    }
    columns.push(`${f.name.padEnd(20)} ${fieldKindToSqlType(f)}`);
  }

  const identifierErrors: string[] = [];
  guardIdentifier(tableName, `table for entity '${entity.slug}'`, identifierErrors);

  const indexes: string[] = [];
  const tenantIdxName = `${tableName}_tenant_idx`;
  const moduleIdxName = `${tableName}_module_idx`;
  guardIdentifier(tenantIdxName, `tenant index on '${entity.slug}'`, identifierErrors);
  guardIdentifier(moduleIdxName, `module index on '${entity.slug}'`, identifierErrors);
  indexes.push(
    `CREATE INDEX IF NOT EXISTS ${tenantIdxName} ON ${tableName} (tenant_id) WHERE deleted_at IS NULL;`,
  );
  indexes.push(
    `CREATE INDEX IF NOT EXISTS ${moduleIdxName} ON ${tableName} (module_id, tenant_id) WHERE deleted_at IS NULL;`,
  );
  for (const f of entity.fields) {
    if (f.kind !== 'money' && 'index' in f && f.index === true) {
      const fieldIdxName = `${tableName}_${f.name}_idx`;
      guardIdentifier(
        fieldIdxName,
        `index on '${entity.slug}.${f.name}'`,
        identifierErrors,
      );
      indexes.push(
        `CREATE INDEX IF NOT EXISTS ${fieldIdxName} ON ${tableName} (${f.name});`,
      );
    }
  }

  const sql = [
    `-- ─────────────────────────────────────────────────────────`,
    `-- Entity: ${entity.slug}  (display: ${entity.display_name_en})`,
    `-- ─────────────────────────────────────────────────────────`,
    ...moneyMarkers,
    `CREATE TABLE IF NOT EXISTS ${tableName} (`,
    columns.map((c) => `  ${c}`).join(',\n'),
    `);`,
    ...indexes,
  ].join('\n');

  return {
    sql,
    tableName,
    identifierErrors: Object.freeze([...identifierErrors]),
  };
}

/**
 * Reject any emitted identifier that exceeds the Postgres 63-byte limit.
 * Two distinct logical identifiers sharing their first 63 bytes would
 * silently collide into one physical object — a data-mixing hazard.
 */
function guardIdentifier(
  name: string,
  context: string,
  sink: string[],
): void {
  if (exceedsPgIdentifierLimit(name)) {
    sink.push(
      `identifier exceeds Postgres ${PG_IDENTIFIER_MAX_BYTES}-byte limit (${context}): ${name}`,
    );
  }
}

function buildWorkflowSeed(spec: ModuleSpec, tenantId: string): string {
  if (spec.workflows.length === 0) {
    return `-- no workflows declared in this spec.`;
  }
  // The spec engine emits a comment manifest — actual workflow
  // execution happens through the kernel's plan-decomposer using
  // these slugs as canonical labels.
  const lines: string[] = [
    `-- ─────────────────────────────────────────────────────────`,
    `-- Workflow manifest (tenant: ${tenantId})`,
    `-- ─────────────────────────────────────────────────────────`,
  ];
  for (const w of spec.workflows) {
    lines.push(
      `--   workflow ${w.slug}: ${w.title}`,
      `--     trigger: ${w.trigger_entity} on ${w.trigger_event}`,
      `--     steps:   ${w.steps.join(' → ')}`,
    );
  }
  return lines.join('\n');
}

function buildUiLayout(spec: ModuleSpec): CompileResult['uiLayout'] {
  const sections = spec.ui_sections.map((s) =>
    s.kind === 'table'
      ? {
          kind: 'table' as const,
          entity: s.entity,
          columns: Object.freeze([...s.columns]),
        }
      : s.kind === 'form'
        ? {
            kind: 'form' as const,
            entity: s.entity,
          }
        : {
            kind: 'kpi_tile' as const,
            title: s.title,
            query: s.query,
          },
  );
  return Object.freeze({ sections: Object.freeze(sections) });
}

function buildZodValidatorTree(
  entity: ReturnType<typeof spec_entity>,
): ZodValidatorTree {
  const fields: Record<string, ZodFieldTree> = {};
  for (const f of entity.fields) {
    fields[f.name] = serialiseFieldToZodTree(f);
  }
  return Object.freeze({
    kind: 'object',
    fields: Object.freeze(fields),
  });
}

function serialiseFieldToZodTree(f: FieldDecl): ZodFieldTree {
  // Build deterministically so the JSON matches across compile runs.
  switch (f.kind) {
    case 'text':
      return {
        kind: 'text',
        required: f.required,
        ...(f.max_length !== undefined ? { max_length: f.max_length } : {}),
      };
    case 'int':
      return {
        kind: 'int',
        required: f.required,
        ...(f.min !== undefined ? { min: f.min } : {}),
        ...(f.max !== undefined ? { max: f.max } : {}),
      };
    case 'numeric':
      return {
        kind: 'numeric',
        required: f.required,
        ...(f.precision !== undefined ? { precision: f.precision } : {}),
        ...(f.scale !== undefined ? { scale: f.scale } : {}),
        ...(f.min !== undefined ? { min: f.min } : {}),
        ...(f.max !== undefined ? { max: f.max } : {}),
      };
    case 'money':
      return { kind: 'money', required: f.required };
    case 'date':
      return { kind: 'date', required: f.required };
    case 'datetime':
      return { kind: 'datetime', required: f.required };
    case 'boolean':
      return { kind: 'boolean', required: f.required };
    case 'fk':
      return { kind: 'fk', required: f.required, references: f.references };
    case 'enum':
      return {
        kind: 'enum',
        required: f.required,
        values: Object.freeze([...f.values]),
      };
    default: {
      // Exhaustiveness guard.
      const exhaust: never = f;
      throw new Error(`unhandled field kind: ${String(exhaust)}`);
    }
  }
}

function fieldKindToSqlType(f: FieldDecl): string {
  const notNull = f.required ? ' NOT NULL' : '';
  switch (f.kind) {
    case 'text':
      return f.max_length !== undefined
        ? `VARCHAR(${f.max_length})${notNull}`
        : `TEXT${notNull}`;
    case 'int':
      return `INTEGER${notNull}`;
    case 'numeric': {
      const p = f.precision ?? 18;
      const s = f.scale ?? 4;
      return `NUMERIC(${p}, ${s})${notNull}`;
    }
    case 'money':
      // Should never reach here — money fields are skipped above.
      return `TEXT /* money fallback */${notNull}`;
    case 'date':
      return `DATE${notNull}`;
    case 'datetime':
      return `TIMESTAMPTZ${notNull}`;
    case 'boolean':
      return `BOOLEAN${notNull}`;
    case 'fk':
      // We emit a soft TEXT pointer — the compiler can't know the
      // target table at codegen time without doing a second pass; the
      // orchestrator validates referential integrity at insert time.
      return `TEXT${notNull}`;
    case 'enum':
      // Enum membership is NOT enforced via a column-level CHECK: the
      // ddl-guard forbids author CHECK expressions (they execute SQL at
      // write-time). The serialised Zod validator enforces the closed
      // value set at every module write path instead. The column is a
      // plain TEXT pointer.
      return `TEXT${notNull}`;
    default: {
      const exhaust: never = f;
      throw new Error(`unhandled field kind for SQL emission: ${String(exhaust)}`);
    }
  }
}

/**
 * Canonical tenant-module table name. MUST byte-match the ddl-guard's
 * `canonicalTenantTablePrefix(tenantId)` + slug — the orchestrator's
 * `isTenantNamespacedTable` check rejects anything else.
 */
function entityTableName(tenantId: string, entitySlug: string): string {
  return `tenant_mod_${tenantId}_${entitySlug}`;
}

/**
 * Reject anything that isn't a strict slug-shaped tenant_id. tenant_id
 * is FK-validated upstream but we still defend in depth — a malicious
 * caller cannot land arbitrary text in the generated table name.
 */
function isValidTenantSlug(tenantId: string): boolean {
  return SLUG_REGEX.test(tenantId);
}

// Type helper — exposes the entity decl shape without re-importing.
type Entity = ModuleSpec['entities'][number];
function spec_entity(): Entity {
  throw new Error('type-only helper');
}
