-- =============================================================================
-- Migration 0188 — Owner onboarding signup persistence
--
-- Replaces the module-level in-memory Maps in
-- services/api-gateway/src/routes/onboarding.router.ts (KI-013) with three
-- durable tables:
--
--   owner_onboarding_credentials
--     One row per tenant created at /signup. Stores the bcrypt password hash,
--     verified-at timestamp, and email. UNIQUE(email) enforces cross-tenant
--     email dedup at the DB layer: the signup INSERT fails on a dup and the
--     route returns 409 — no cross-tenant SELECT is ever needed.
--
--   onboarding_signup_sessions
--     The onboarding flow session (one per tenant). Carries a session_token
--     minted post-email-verification, the 8-step checklist (jsonb), and all
--     optional progress fields (first_site_id, first_chat_thread_id, etc.).
--
--   onboarding_email_verifications
--     One-shot email-verification tokens. token is the 32-byte base64url value
--     generated by /signup and consumed exactly once by /verify-email.
--
-- ── SECURITY MODEL ────────────────────────────────────────────────────────────
-- This is a PRE-TENANT flow: /signup creates the tenant row, so there is NO
-- app.current_tenant_id GUC bound when these rows are first written.
-- Email-dedup (unique-violation on insert) and token lookup are inherently
-- un-tenant-scoped by design.
--
-- Therefore tenant-GUC RLS is NOT the isolation mechanism for these tables.
-- Security is enforced by:
--   (a) UNIQUE(email) — prevents duplicate-email signups at the DB level.
--   (b) Unguessable 32-byte base64url token — prevents token forgery.
--   (c) bcrypt hash — prevents password exposure even on DB breach.
--   (d) consumed_at timestamp — enforces one-shot token semantics at the app
--       layer (the row remains for audit; the consumed check happens in code).
--
-- We still ENABLE + FORCE ROW LEVEL SECURITY on all three tables and add a
-- permissive service-managed policy (USING true WITH CHECK true) so the tables
-- comply with the CLAUDE.md "RLS is FORCE-enabled on every tenant-scoped table"
-- hard rule. These are analogous to Supabase's auth.users / auth.sessions
-- tables that service_role manages without a per-tenant GUC filter.
--
-- Idempotent (IF NOT EXISTS + DO blocks). Safe to re-run.
-- IMMUTABLE: per CLAUDE.md "Migrations are immutable" — never edit this file
-- after merge; append a new numbered file instead.
-- =============================================================================

BEGIN;

-- ─── Table 1: owner_onboarding_credentials ───────────────────────────────────

CREATE TABLE IF NOT EXISTS owner_onboarding_credentials (
  -- tenant_id is BOTH the primary key and a logical FK to tenants(id).
  -- We reference tenants(id) so the FK is enforced, but ON DELETE CASCADE
  -- is deliberately omitted here: the signup flow creates the tenant row
  -- inside this same request, and we want the credential to survive an
  -- accidental tenant soft-delete during onboarding.
  tenant_id           text        PRIMARY KEY,
  owner_user_id       text        NOT NULL,
  -- Normalized (trim + lower) email. UNIQUE enforces cross-tenant dedup.
  email               text        NOT NULL,
  password_hash       text        NOT NULL,
  email_verified_at   timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now()
);

-- Cross-tenant email dedup — INSERT fails on dup; route returns 409.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'owner_onboarding_credentials_email_key'
       AND conrelid = 'owner_onboarding_credentials'::regclass
  ) THEN
    ALTER TABLE owner_onboarding_credentials
      ADD CONSTRAINT owner_onboarding_credentials_email_key UNIQUE (email);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_ooc_tenant_id
  ON owner_onboarding_credentials (tenant_id);

ALTER TABLE owner_onboarding_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE owner_onboarding_credentials FORCE  ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname = 'public'
       AND tablename  = 'owner_onboarding_credentials'
       AND policyname = 'onboarding_signup_service_managed'
  ) THEN
    -- Service-managed policy: the api-gateway service_role connection owns
    -- these rows. No per-tenant GUC filter — see SECURITY MODEL above.
    CREATE POLICY onboarding_signup_service_managed
      ON owner_onboarding_credentials
      FOR ALL
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

-- ─── Table 2: onboarding_signup_sessions ─────────────────────────────────────

CREATE TABLE IF NOT EXISTS onboarding_signup_sessions (
  -- One row per tenant. tenant_id is both PK and FK.
  tenant_id           text        PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,
  id                  text        NOT NULL,
  owner_user_id       text        NOT NULL,
  email               text        NOT NULL,
  business_name       text        NOT NULL,
  country             text        NOT NULL,
  -- NULL until email is verified; minted by /verify-email.
  session_token       text,
  -- 8-step onboarding checklist as a jsonb array of OnboardingFlowStep objects.
  steps               jsonb       NOT NULL,
  intent              text,
  first_site_id       text,
  first_chat_thread_id text,
  suggested_skills    jsonb,
  created_at          timestamptz NOT NULL DEFAULT now()
);

-- Allow O(1) lookups by session_token (the FE sends this header on every call).
CREATE INDEX IF NOT EXISTS idx_oss_session_token
  ON onboarding_signup_sessions (session_token)
  WHERE session_token IS NOT NULL;

ALTER TABLE onboarding_signup_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE onboarding_signup_sessions FORCE  ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname = 'public'
       AND tablename  = 'onboarding_signup_sessions'
       AND policyname = 'onboarding_signup_service_managed'
  ) THEN
    CREATE POLICY onboarding_signup_service_managed
      ON onboarding_signup_sessions
      FOR ALL
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

-- ─── Table 3: onboarding_email_verifications ─────────────────────────────────

CREATE TABLE IF NOT EXISTS onboarding_email_verifications (
  -- The 32-byte base64url token IS the primary key (unguessable, low collision).
  token               text        PRIMARY KEY,
  tenant_id           text        NOT NULL,
  email               text        NOT NULL,
  issued_at           timestamptz NOT NULL DEFAULT now(),
  -- NULL = not yet consumed; non-NULL = consumed at this timestamp.
  -- The row is kept for audit; the consumed check happens at the app layer.
  consumed_at         timestamptz
);

ALTER TABLE onboarding_email_verifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE onboarding_email_verifications FORCE  ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname = 'public'
       AND tablename  = 'onboarding_email_verifications'
       AND policyname = 'onboarding_signup_service_managed'
  ) THEN
    CREATE POLICY onboarding_signup_service_managed
      ON onboarding_email_verifications
      FOR ALL
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

-- ─── Lock down: SERVICE-MANAGED ONLY (never exposed via the Supabase REST API).
-- These pre-tenant tables hold password hashes + verification secrets, and the
-- RLS policy above is permissive (USING true) because there is no tenant GUC to
-- gate on. Isolation therefore MUST come from table-level grants: revoke all
-- access from the PostgREST API roles (anon, authenticated) so a `USING(true)`
-- policy can never serve a password hash over the public API. Only the gateway's
-- privileged DB connection (and BYPASSRLS service_role) may touch these rows.
-- Guarded by role existence so the migration also applies on a vanilla PG.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON owner_onboarding_credentials   FROM anon;
    REVOKE ALL ON onboarding_signup_sessions      FROM anon;
    REVOKE ALL ON onboarding_email_verifications  FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON owner_onboarding_credentials   FROM authenticated;
    REVOKE ALL ON onboarding_signup_sessions      FROM authenticated;
    REVOKE ALL ON onboarding_email_verifications  FROM authenticated;
  END IF;
END $$;

COMMIT;
