/**
 * Action catalog — typed, immutable library of possible business actions.
 *
 * Templates are grouped by domain (sales, ops, hr, finance, customer-success,
 * compliance, learning, marketing, product). Each entry encodes baseline
 * ICE / RICE inputs that the scorers lift by snapshot context.
 *
 * This file ships data only — no side effects, no I/O.
 *
 * @module features/central-command/md/nba/action-catalog
 */

import type { ActionTemplate, ActionDomain } from "./types";

/** Build a frozen template — keeps the catalog immutable. */
function template(t: ActionTemplate): ActionTemplate {
  return Object.freeze({
    ...t,
    triggers: Object.freeze([...t.triggers]),
    tags: Object.freeze([...t.tags]),
  });
}

// ---------------------------------------------------------------------------
// Customer success (8)
// ---------------------------------------------------------------------------

const customerSuccessActions: readonly ActionTemplate[] = Object.freeze([
  template({
    id: "cs.send-nps-survey-top10",
    domain: "customer-success",
    title: "Send NPS survey to top 10 customers",
    description: "Trigger a quarterly NPS pulse to your top-revenue customers.",
    baselineImpact: 7,
    baselineEase: 9,
    baselineConfidence: 0.8,
    baselineReach: 10,
    effortPersonDays: 0.5,
    effortBucket: "trivial",
    triggers: [{ kind: "always" }],
    tags: ["nps", "voice-of-customer"],
  }),
  template({
    id: "cs.respond-detractor-nps",
    domain: "customer-success",
    title: "Personally respond to NPS detractor",
    description:
      "Call detractor and run a 15-minute discovery on the root cause.",
    baselineImpact: 8,
    baselineEase: 7,
    baselineConfidence: 0.75,
    baselineReach: 1,
    effortPersonDays: 0.5,
    effortBucket: "trivial",
    triggers: [{ kind: "nps-drop", threshold: 6 }],
    tags: ["nps", "retention", "save"],
  }),
  template({
    id: "cs.follow-up-complaint",
    domain: "customer-success",
    title: "Follow up on open customer complaint",
    description: "Close the loop on the open complaint with the customer.",
    baselineImpact: 8,
    baselineEase: 7,
    baselineConfidence: 0.85,
    baselineReach: 1,
    effortPersonDays: 0.25,
    effortBucket: "trivial",
    triggers: [{ kind: "complaint-open", threshold: 1 }],
    tags: ["retention", "complaint"],
  }),
  template({
    id: "cs.qbr-top-account",
    domain: "customer-success",
    title: "Schedule QBR with top account",
    description:
      "Run a quarterly business review with the largest ARR account.",
    baselineImpact: 8,
    baselineEase: 5,
    baselineConfidence: 0.75,
    baselineReach: 1,
    effortPersonDays: 2,
    effortBucket: "medium",
    triggers: [{ kind: "always" }],
    tags: ["qbr", "expansion"],
  }),
  template({
    id: "cs.reactivate-dormant",
    domain: "customer-success",
    title: "Reactivate dormant customer",
    description: "Reach out to a customer with no contact in 60+ days.",
    baselineImpact: 6,
    baselineEase: 8,
    baselineConfidence: 0.5,
    baselineReach: 1,
    effortPersonDays: 0.25,
    effortBucket: "trivial",
    triggers: [{ kind: "always" }],
    tags: ["retention", "dormant"],
  }),
  template({
    id: "cs.respond-feedback",
    domain: "customer-success",
    title: "Respond to recent feedback",
    description: "Reply to recent customer feedback within 48h SLA.",
    baselineImpact: 6,
    baselineEase: 9,
    baselineConfidence: 0.8,
    baselineReach: 5,
    effortPersonDays: 0.25,
    effortBucket: "trivial",
    triggers: [{ kind: "always" }],
    tags: ["feedback"],
  }),
  template({
    id: "cs.send-csat-pulse",
    domain: "customer-success",
    title: "Send CSAT pulse",
    description: "Send a single-question CSAT to all active customers.",
    baselineImpact: 5,
    baselineEase: 9,
    baselineConfidence: 0.8,
    baselineReach: 50,
    effortPersonDays: 0.25,
    effortBucket: "trivial",
    triggers: [{ kind: "csat-drop", threshold: 4 }],
    tags: ["csat"],
  }),
  template({
    id: "cs.launch-referral-program",
    domain: "customer-success",
    title: "Launch referral program for promoters",
    description: "Invite NPS promoters into a referral program.",
    baselineImpact: 7,
    baselineEase: 5,
    baselineConfidence: 0.6,
    baselineReach: 20,
    effortPersonDays: 3,
    effortBucket: "medium",
    triggers: [{ kind: "always" }],
    tags: ["growth", "referral"],
  }),
]);

// ---------------------------------------------------------------------------
// Sales (8)
// ---------------------------------------------------------------------------

const salesActions: readonly ActionTemplate[] = Object.freeze([
  template({
    id: "sales.reach-stalled-lead",
    domain: "sales",
    title: "Reach out to stalled lead",
    description: "Move a high-value lead that has been stuck in stage.",
    baselineImpact: 8,
    baselineEase: 8,
    baselineConfidence: 0.55,
    baselineReach: 1,
    effortPersonDays: 0.25,
    effortBucket: "trivial",
    triggers: [{ kind: "pipeline-stalled", threshold: 14 }],
    tags: ["pipeline", "sales"],
  }),
  template({
    id: "sales.discovery-call-new-lead",
    domain: "sales",
    title: "Run discovery call with new lead",
    description: "Schedule a 30-min discovery with the most recent inbound.",
    baselineImpact: 7,
    baselineEase: 7,
    baselineConfidence: 0.6,
    baselineReach: 1,
    effortPersonDays: 0.5,
    effortBucket: "trivial",
    triggers: [{ kind: "always" }],
    tags: ["sales", "discovery"],
  }),
  template({
    id: "sales.send-proposal",
    domain: "sales",
    title: "Send proposal to qualified lead",
    description: "Draft and send a proposal for a lead past discovery.",
    baselineImpact: 9,
    baselineEase: 5,
    baselineConfidence: 0.65,
    baselineReach: 1,
    effortPersonDays: 1.5,
    effortBucket: "medium",
    triggers: [{ kind: "always" }],
    tags: ["proposal", "sales"],
  }),
  template({
    id: "sales.close-call-late-stage",
    domain: "sales",
    title: "Run close call on late-stage opportunity",
    description: "Drive a late-stage opp to commit with a focused close call.",
    baselineImpact: 9,
    baselineEase: 6,
    baselineConfidence: 0.7,
    baselineReach: 1,
    effortPersonDays: 0.5,
    effortBucket: "trivial",
    triggers: [{ kind: "always" }],
    tags: ["sales", "close"],
  }),
  template({
    id: "sales.upsell-expansion",
    domain: "sales",
    title: "Open upsell conversation with happy customer",
    description: "Pitch the next-tier offering to a high-NPS customer.",
    baselineImpact: 8,
    baselineEase: 7,
    baselineConfidence: 0.6,
    baselineReach: 1,
    effortPersonDays: 0.5,
    effortBucket: "trivial",
    triggers: [{ kind: "always" }],
    tags: ["expansion", "upsell"],
  }),
  template({
    id: "sales.win-loss-review",
    domain: "sales",
    title: "Run win/loss review for last 10 deals",
    description: "Interview reps + customers on what drove wins vs losses.",
    baselineImpact: 7,
    baselineEase: 4,
    baselineConfidence: 0.7,
    baselineReach: 10,
    effortPersonDays: 4,
    effortBucket: "large",
    triggers: [{ kind: "always" }],
    tags: ["learning", "sales-ops"],
  }),
  template({
    id: "sales.tighten-icp",
    domain: "sales",
    title: "Re-define ICP from last 20 closed-won",
    description: "Refresh the Ideal Customer Profile using recent wins.",
    baselineImpact: 8,
    baselineEase: 4,
    baselineConfidence: 0.65,
    baselineReach: 50,
    effortPersonDays: 3,
    effortBucket: "medium",
    triggers: [{ kind: "always" }],
    tags: ["positioning", "icp"],
  }),
  template({
    id: "sales.qualify-aging-lead",
    domain: "sales",
    title: "Qualify or kill aging lead",
    description: "Force a yes/no on a lead older than 30 days.",
    baselineImpact: 5,
    baselineEase: 9,
    baselineConfidence: 0.7,
    baselineReach: 1,
    effortPersonDays: 0.1,
    effortBucket: "trivial",
    triggers: [{ kind: "lead-aging", threshold: 30 }],
    tags: ["pipeline-hygiene"],
  }),
]);

// ---------------------------------------------------------------------------
// HR / people (8)
// ---------------------------------------------------------------------------

const hrActions: readonly ActionTemplate[] = Object.freeze([
  template({
    id: "hr.schedule-1on1",
    domain: "hr",
    title: "Schedule 1-on-1 with employee",
    description: "Book a 1-on-1 with an employee who hasn't had one in 90d+.",
    baselineImpact: 7,
    baselineEase: 9,
    baselineConfidence: 0.85,
    baselineReach: 1,
    effortPersonDays: 0.25,
    effortBucket: "trivial",
    triggers: [{ kind: "employee-1on1-overdue", threshold: 90 }],
    tags: ["people", "retention"],
  }),
  template({
    id: "hr.onboarding-plan",
    domain: "hr",
    title: "Build 30/60/90 onboarding plan for new hire",
    description: "Create the structured onboarding plan for a new hire.",
    baselineImpact: 8,
    baselineEase: 6,
    baselineConfidence: 0.8,
    baselineReach: 1,
    effortPersonDays: 1,
    effortBucket: "small",
    triggers: [{ kind: "new-hire-onboarding" }],
    tags: ["onboarding", "new-hire"],
  }),
  template({
    id: "hr.recognize-top-performer",
    domain: "hr",
    title: "Recognize top performer publicly",
    description: "Call out a top performer in the company channel.",
    baselineImpact: 6,
    baselineEase: 9,
    baselineConfidence: 0.85,
    baselineReach: 30,
    effortPersonDays: 0.1,
    effortBucket: "trivial",
    triggers: [{ kind: "always" }],
    tags: ["culture", "recognition"],
  }),
  template({
    id: "hr.skip-level-meeting",
    domain: "hr",
    title: "Run skip-level meeting",
    description: "Schedule a skip-level with an IC two levels down.",
    baselineImpact: 6,
    baselineEase: 7,
    baselineConfidence: 0.7,
    baselineReach: 5,
    effortPersonDays: 0.5,
    effortBucket: "trivial",
    triggers: [{ kind: "always" }],
    tags: ["culture", "leadership"],
  }),
  template({
    id: "hr.update-job-description",
    domain: "hr",
    title: "Update open-role job description",
    description: "Refresh a JD that has been live for 30+ days without hires.",
    baselineImpact: 5,
    baselineEase: 7,
    baselineConfidence: 0.6,
    baselineReach: 1,
    effortPersonDays: 0.5,
    effortBucket: "trivial",
    triggers: [{ kind: "always" }],
    tags: ["hiring"],
  }),
  template({
    id: "hr.run-engagement-pulse",
    domain: "hr",
    title: "Run engagement pulse survey",
    description: "Send a 3-question pulse on engagement to all employees.",
    baselineImpact: 6,
    baselineEase: 8,
    baselineConfidence: 0.75,
    baselineReach: 50,
    effortPersonDays: 0.5,
    effortBucket: "trivial",
    triggers: [{ kind: "always" }],
    tags: ["engagement"],
  }),
  template({
    id: "hr.career-conversation",
    domain: "hr",
    title: "Run career conversation with high-potential",
    description: "Dedicated career chat with a high-potential employee.",
    baselineImpact: 7,
    baselineEase: 7,
    baselineConfidence: 0.75,
    baselineReach: 1,
    effortPersonDays: 0.5,
    effortBucket: "trivial",
    triggers: [{ kind: "always" }],
    tags: ["retention", "growth"],
  }),
  template({
    id: "hr.exit-risk-conversation",
    domain: "hr",
    title: "Address exit-risk employee",
    description: "Talk to an employee flagged as at risk of leaving.",
    baselineImpact: 9,
    baselineEase: 6,
    baselineConfidence: 0.6,
    baselineReach: 1,
    effortPersonDays: 0.5,
    effortBucket: "trivial",
    triggers: [{ kind: "always" }],
    tags: ["retention", "save"],
  }),
]);

// ---------------------------------------------------------------------------
// Finance (7)
// ---------------------------------------------------------------------------

const financeActions: readonly ActionTemplate[] = Object.freeze([
  template({
    id: "fin.chase-overdue-invoice",
    domain: "finance",
    title: "Chase overdue invoice",
    description: "Send a polite reminder for an invoice past due.",
    baselineImpact: 7,
    baselineEase: 9,
    baselineConfidence: 0.85,
    baselineReach: 1,
    effortPersonDays: 0.1,
    effortBucket: "trivial",
    triggers: [{ kind: "invoice-overdue", threshold: 1 }],
    tags: ["cash"],
  }),
  template({
    id: "fin.cash-runway-review",
    domain: "finance",
    title: "Run cash-runway review",
    description: "Re-forecast cash burn and refresh runway estimate.",
    baselineImpact: 9,
    baselineEase: 5,
    baselineConfidence: 0.8,
    baselineReach: 1,
    effortPersonDays: 1,
    effortBucket: "small",
    triggers: [{ kind: "cash-runway-low", threshold: 6 }],
    tags: ["cash", "planning"],
  }),
  template({
    id: "fin.renegotiate-payment-terms",
    domain: "finance",
    title: "Renegotiate payment terms with largest vendor",
    description: "Push largest vendor from net-30 to net-60.",
    baselineImpact: 7,
    baselineEase: 5,
    baselineConfidence: 0.5,
    baselineReach: 1,
    effortPersonDays: 1,
    effortBucket: "small",
    triggers: [{ kind: "cash-runway-low", threshold: 9 }],
    tags: ["cash", "vendor"],
  }),
  template({
    id: "fin.expense-audit",
    domain: "finance",
    title: "Audit last quarter's expenses",
    description: "Run a quick audit on last quarter's spend by category.",
    baselineImpact: 6,
    baselineEase: 5,
    baselineConfidence: 0.7,
    baselineReach: 1,
    effortPersonDays: 2,
    effortBucket: "medium",
    triggers: [{ kind: "always" }],
    tags: ["cost"],
  }),
  template({
    id: "fin.refresh-financial-model",
    domain: "finance",
    title: "Refresh 13-week cashflow model",
    description: "Update the rolling 13-week cashflow with latest actuals.",
    baselineImpact: 7,
    baselineEase: 6,
    baselineConfidence: 0.8,
    baselineReach: 1,
    effortPersonDays: 1,
    effortBucket: "small",
    triggers: [{ kind: "always" }],
    tags: ["cash", "forecast"],
  }),
  template({
    id: "fin.bank-relationship-check",
    domain: "finance",
    title: "Check in with banking partner",
    description: "Touch base with primary banker on credit facility.",
    baselineImpact: 5,
    baselineEase: 8,
    baselineConfidence: 0.6,
    baselineReach: 1,
    effortPersonDays: 0.25,
    effortBucket: "trivial",
    triggers: [{ kind: "always" }],
    tags: ["banking"],
  }),
  template({
    id: "fin.pricing-review",
    domain: "finance",
    title: "Review pricing for stale SKU",
    description: "Re-evaluate pricing on a product line untouched 12+ months.",
    baselineImpact: 8,
    baselineEase: 5,
    baselineConfidence: 0.6,
    baselineReach: 30,
    effortPersonDays: 2,
    effortBucket: "medium",
    triggers: [{ kind: "always" }],
    tags: ["pricing"],
  }),
]);

// ---------------------------------------------------------------------------
// Ops / supplier (6)
// ---------------------------------------------------------------------------

const opsActions: readonly ActionTemplate[] = Object.freeze([
  template({
    id: "ops.review-supplier-contract",
    domain: "ops",
    title: "Review expiring supplier contract",
    description: "Renew or renegotiate a contract expiring in <30 days.",
    baselineImpact: 7,
    baselineEase: 6,
    baselineConfidence: 0.75,
    baselineReach: 1,
    effortPersonDays: 1,
    effortBucket: "small",
    triggers: [{ kind: "contract-expiring", threshold: 30 }],
    tags: ["procurement"],
  }),
  template({
    id: "ops.dual-source-critical-supplier",
    domain: "ops",
    title: "Dual-source critical supplier",
    description:
      "Identify a second source for a single-sourced critical supplier.",
    baselineImpact: 8,
    baselineEase: 4,
    baselineConfidence: 0.55,
    baselineReach: 1,
    effortPersonDays: 5,
    effortBucket: "large",
    triggers: [{ kind: "always" }],
    tags: ["risk", "procurement"],
  }),
  template({
    id: "ops.kpi-review",
    domain: "ops",
    title: "Run KPI off-target review",
    description: "Diagnose root cause for an off-target operational KPI.",
    baselineImpact: 8,
    baselineEase: 5,
    baselineConfidence: 0.7,
    baselineReach: 1,
    effortPersonDays: 2,
    effortBucket: "medium",
    triggers: [{ kind: "kpi-off-target" }],
    tags: ["operations"],
  }),
  template({
    id: "ops.automate-manual-task",
    domain: "ops",
    title: "Automate a recurring manual task",
    description: "Find a weekly manual task and automate it.",
    baselineImpact: 6,
    baselineEase: 5,
    baselineConfidence: 0.65,
    baselineReach: 5,
    effortPersonDays: 3,
    effortBucket: "medium",
    triggers: [{ kind: "always" }],
    tags: ["automation"],
  }),
  template({
    id: "ops.process-map-review",
    domain: "ops",
    title: "Walk the gemba for a key process",
    description: "Observe one core operational process end-to-end.",
    baselineImpact: 6,
    baselineEase: 6,
    baselineConfidence: 0.6,
    baselineReach: 1,
    effortPersonDays: 1,
    effortBucket: "small",
    triggers: [{ kind: "always" }],
    tags: ["process"],
  }),
  template({
    id: "ops.incident-postmortem",
    domain: "ops",
    title: "Run postmortem on last incident",
    description:
      "Blameless postmortem on the most recent operational incident.",
    baselineImpact: 7,
    baselineEase: 6,
    baselineConfidence: 0.75,
    baselineReach: 1,
    effortPersonDays: 1,
    effortBucket: "small",
    triggers: [{ kind: "always" }],
    tags: ["reliability"],
  }),
]);

// ---------------------------------------------------------------------------
// Compliance (5)
// ---------------------------------------------------------------------------

const complianceActions: readonly ActionTemplate[] = Object.freeze([
  template({
    id: "compliance.submit-filing",
    domain: "compliance",
    title: "Submit upcoming regulatory filing",
    description: "File the regulatory submission due in <14 days.",
    baselineImpact: 9,
    baselineEase: 6,
    baselineConfidence: 0.9,
    baselineReach: 1,
    effortPersonDays: 1.5,
    effortBucket: "medium",
    triggers: [{ kind: "compliance-deadline", threshold: 14 }],
    tags: ["regulatory"],
  }),
  template({
    id: "compliance.policy-refresh",
    domain: "compliance",
    title: "Refresh annual policy",
    description: "Update the annual compliance policy doc.",
    baselineImpact: 5,
    baselineEase: 5,
    baselineConfidence: 0.7,
    baselineReach: 50,
    effortPersonDays: 2,
    effortBucket: "medium",
    triggers: [{ kind: "always" }],
    tags: ["policy"],
  }),
  template({
    id: "compliance.access-review",
    domain: "compliance",
    title: "Run quarterly access review",
    description: "Validate user access permissions across critical systems.",
    baselineImpact: 7,
    baselineEase: 5,
    baselineConfidence: 0.75,
    baselineReach: 50,
    effortPersonDays: 2,
    effortBucket: "medium",
    triggers: [{ kind: "always" }],
    tags: ["security", "audit"],
  }),
  template({
    id: "compliance.train-on-policy",
    domain: "compliance",
    title: "Roll out annual policy training",
    description: "Push annual compliance training to all employees.",
    baselineImpact: 6,
    baselineEase: 6,
    baselineConfidence: 0.7,
    baselineReach: 50,
    effortPersonDays: 1,
    effortBucket: "small",
    triggers: [{ kind: "always" }],
    tags: ["training"],
  }),
  template({
    id: "compliance.audit-prep",
    domain: "compliance",
    title: "Prep for upcoming audit",
    description: "Pre-stage evidence and walkthrough for next audit.",
    baselineImpact: 8,
    baselineEase: 4,
    baselineConfidence: 0.8,
    baselineReach: 1,
    effortPersonDays: 5,
    effortBucket: "large",
    triggers: [{ kind: "compliance-deadline", threshold: 60 }],
    tags: ["audit"],
  }),
]);

// ---------------------------------------------------------------------------
// Learning (4)
// ---------------------------------------------------------------------------

const learningActions: readonly ActionTemplate[] = Object.freeze([
  template({
    id: "learning.nudge-incomplete-track",
    domain: "learning",
    title: "Nudge employees with stalled learning track",
    description: "Send a reminder to employees below 50% completion.",
    baselineImpact: 4,
    baselineEase: 9,
    baselineConfidence: 0.7,
    baselineReach: 10,
    effortPersonDays: 0.25,
    effortBucket: "trivial",
    triggers: [{ kind: "training-completion-low", threshold: 50 }],
    tags: ["enablement"],
  }),
  template({
    id: "learning.book-conference",
    domain: "learning",
    title: "Book strategic industry conference",
    description: "Book a 2026 conference slot for the leadership team.",
    baselineImpact: 5,
    baselineEase: 7,
    baselineConfidence: 0.6,
    baselineReach: 3,
    effortPersonDays: 0.5,
    effortBucket: "trivial",
    triggers: [{ kind: "always" }],
    tags: ["growth"],
  }),
  template({
    id: "learning.run-internal-lt",
    domain: "learning",
    title: "Run internal lunch-and-learn",
    description: "Host a lunch-and-learn from a team member.",
    baselineImpact: 4,
    baselineEase: 8,
    baselineConfidence: 0.7,
    baselineReach: 20,
    effortPersonDays: 0.5,
    effortBucket: "trivial",
    triggers: [{ kind: "always" }],
    tags: ["culture"],
  }),
  template({
    id: "learning.assign-mentorship",
    domain: "learning",
    title: "Pair employee with mentor",
    description: "Match a high-potential employee with an internal mentor.",
    baselineImpact: 6,
    baselineEase: 7,
    baselineConfidence: 0.65,
    baselineReach: 2,
    effortPersonDays: 0.5,
    effortBucket: "trivial",
    triggers: [{ kind: "always" }],
    tags: ["retention", "growth"],
  }),
]);

// ---------------------------------------------------------------------------
// Marketing (5) + product (5)
// ---------------------------------------------------------------------------

const marketingActions: readonly ActionTemplate[] = Object.freeze([
  template({
    id: "mkt.publish-case-study",
    domain: "marketing",
    title: "Publish case study from happy customer",
    description: "Turn a high-NPS account into a published case study.",
    baselineImpact: 7,
    baselineEase: 5,
    baselineConfidence: 0.65,
    baselineReach: 200,
    effortPersonDays: 3,
    effortBucket: "medium",
    triggers: [{ kind: "always" }],
    tags: ["content", "credibility"],
  }),
  template({
    id: "mkt.refresh-website-hero",
    domain: "marketing",
    title: "Refresh website hero copy",
    description: "Update the hero copy with the latest positioning.",
    baselineImpact: 6,
    baselineEase: 7,
    baselineConfidence: 0.55,
    baselineReach: 1000,
    effortPersonDays: 1,
    effortBucket: "small",
    triggers: [{ kind: "always" }],
    tags: ["positioning"],
  }),
  template({
    id: "mkt.run-paid-experiment",
    domain: "marketing",
    title: "Run paid acquisition experiment",
    description: "Launch a small paid test on top channel.",
    baselineImpact: 7,
    baselineEase: 5,
    baselineConfidence: 0.45,
    baselineReach: 500,
    effortPersonDays: 2,
    effortBucket: "medium",
    triggers: [{ kind: "always" }],
    tags: ["growth", "paid"],
  }),
  template({
    id: "mkt.relaunch-newsletter",
    domain: "marketing",
    title: "Send newsletter to lapsed list",
    description: "Re-engage the newsletter list with a value-first send.",
    baselineImpact: 5,
    baselineEase: 8,
    baselineConfidence: 0.6,
    baselineReach: 1000,
    effortPersonDays: 1,
    effortBucket: "small",
    triggers: [{ kind: "always" }],
    tags: ["nurture"],
  }),
  template({
    id: "mkt.post-thought-leadership",
    domain: "marketing",
    title: "Publish thought-leadership post",
    description: "Author a long-form post from the owner.",
    baselineImpact: 6,
    baselineEase: 6,
    baselineConfidence: 0.55,
    baselineReach: 300,
    effortPersonDays: 1,
    effortBucket: "small",
    triggers: [{ kind: "always" }],
    tags: ["content", "owner-voice"],
  }),
]);

const productActions: readonly ActionTemplate[] = Object.freeze([
  template({
    id: "product.ship-most-requested",
    domain: "product",
    title: "Ship the #1 customer-requested feature",
    description: "Promote the highest-requested feature to the next sprint.",
    baselineImpact: 9,
    baselineEase: 4,
    baselineConfidence: 0.7,
    baselineReach: 100,
    effortPersonDays: 10,
    effortBucket: "epic",
    triggers: [{ kind: "always" }],
    tags: ["roadmap", "voice-of-customer"],
  }),
  template({
    id: "product.kill-unused-feature",
    domain: "product",
    title: "Sunset unused feature",
    description: "Remove a feature with <2% usage to reduce maintenance.",
    baselineImpact: 5,
    baselineEase: 6,
    baselineConfidence: 0.7,
    baselineReach: 50,
    effortPersonDays: 2,
    effortBucket: "medium",
    triggers: [{ kind: "always" }],
    tags: ["simplify"],
  }),
  template({
    id: "product.usability-test",
    domain: "product",
    title: "Run usability tests on top funnel",
    description: "Five-user usability test on the activation funnel.",
    baselineImpact: 7,
    baselineEase: 5,
    baselineConfidence: 0.7,
    baselineReach: 5,
    effortPersonDays: 2,
    effortBucket: "medium",
    triggers: [{ kind: "always" }],
    tags: ["ux"],
  }),
  template({
    id: "product.fix-top-bug",
    domain: "product",
    title: "Fix highest-frequency bug",
    description: "Resolve the most reported bug from the last 30 days.",
    baselineImpact: 7,
    baselineEase: 6,
    baselineConfidence: 0.8,
    baselineReach: 50,
    effortPersonDays: 1.5,
    effortBucket: "medium",
    triggers: [{ kind: "always" }],
    tags: ["quality"],
  }),
  template({
    id: "product.publish-changelog",
    domain: "product",
    title: "Publish weekly changelog",
    description: "Ship a customer-facing changelog of the past week.",
    baselineImpact: 4,
    baselineEase: 9,
    baselineConfidence: 0.8,
    baselineReach: 200,
    effortPersonDays: 0.25,
    effortBucket: "trivial",
    triggers: [{ kind: "always" }],
    tags: ["transparency"],
  }),
]);

// ---------------------------------------------------------------------------
// Public catalog
// ---------------------------------------------------------------------------

/** Full, immutable catalog (50+ entries). */
export const ACTION_CATALOG: readonly ActionTemplate[] = Object.freeze([
  ...customerSuccessActions,
  ...salesActions,
  ...hrActions,
  ...financeActions,
  ...opsActions,
  ...complianceActions,
  ...learningActions,
  ...marketingActions,
  ...productActions,
]);

/** Templates grouped by domain — handy for the UI. */
export const ACTION_CATALOG_BY_DOMAIN: Readonly<
  Record<ActionDomain, readonly ActionTemplate[]>
> = Object.freeze({
  "customer-success": customerSuccessActions,
  sales: salesActions,
  hr: hrActions,
  finance: financeActions,
  ops: opsActions,
  compliance: complianceActions,
  learning: learningActions,
  marketing: marketingActions,
  product: productActions,
});

/** Lookup helper. Returns null when the id is unknown. */
export function getActionTemplate(id: string): ActionTemplate | null {
  return ACTION_CATALOG.find((t) => t.id === id) ?? null;
}

/** Catalog size — exposed for tests + telemetry. */
export const ACTION_CATALOG_SIZE: number = ACTION_CATALOG.length;
