/**
 * rls-force-injector.ts — HARD RULE 2: RLS-FORCE auto-injection.
 *
 * For EVERY spawned table the guard emits the proven 0306/0165 RLS
 * block — ENABLE + FORCE ROW LEVEL SECURITY, a `tenant_isolation`
 * policy bound to the canonical `app.current_tenant_id` GUC, a
 * `service_role_bypass` policy on `app.is_service_role`, and a
 * pg_roles-guarded `REVOKE ALL ... FROM anon`. A module author cannot
 * opt out: the block is generated by the guard, not by the author, and
 * `verifyRlsForced` rejects any accepted DDL whose spawned tables are
 * not all covered by a conforming block.
 *
 * The GUC string is canonical and load-bearing:
 *   current_setting('app.current_tenant_id', true)
 * (matches api-gateway middleware + migration 0306). A non-canonical
 * GUC (e.g. the legacy `public.current_app_tenant_id()` helper, or any
 * other setting name) is REJECTED so a spawned table can never bind to
 * a GUC the gateway does not set fail-closed.
 *
 * Pure string builders + a structural verifier. No I/O.
 */

import {
  assertTenantIdShape,
  isTenantNamespacedTable,
  stripSchemaQualifier,
} from './identifier-policy.js';

/** Canonical GUCs — must match api-gateway + migration 0306/0165. */
export const TENANT_GUC = "current_setting('app.current_tenant_id', true)";
export const SERVICE_ROLE_GUC = "current_setting('app.is_service_role', true)";

export interface RlsVerifyResult {
  readonly ok: boolean;
  readonly errors: ReadonlyArray<string>;
}

/**
 * Build the canonical FORCE-RLS block for a set of tenant-namespaced
 * tables. Deterministic: tables are emitted in the given order. Throws
 * if any table is not inside the tenant namespace (defence in depth —
 * the caller should only pass validated tables).
 */
export function buildCanonicalRlsBlock(
  tenantId: string,
  tenantNamespacedTables: ReadonlyArray<string>,
): string {
  assertTenantIdShape(tenantId);
  if (tenantNamespacedTables.length === 0) {
    throw new Error('ddl-guard: buildCanonicalRlsBlock requires ≥1 table');
  }
  const bare: string[] = [];
  for (const t of tenantNamespacedTables) {
    const name = stripSchemaQualifier(t);
    if (!isTenantNamespacedTable(name, tenantId)) {
      throw new Error(
        `ddl-guard: refusing to emit RLS for non-namespaced table: ${t}`,
      );
    }
    bare.push(name);
  }

  const tableArray = bare.map((t) => `    '${t}'`).join(',\n');

  return [
    '-- ─────────────────────────────────────────────────────────',
    '-- HARD RULE 2 — auto-injected FORCE-RLS (canonical 0306/0165).',
    '-- tenant_isolation + service_role_bypass + REVOKE anon.',
    '-- A module author cannot opt out of this block.',
    '-- ─────────────────────────────────────────────────────────',
    'DO $ddlguard_rls$',
    'DECLARE',
    '  tbl text;',
    '  tenant_tables text[] := ARRAY[',
    tableArray,
    '  ];',
    'BEGIN',
    '  FOREACH tbl IN ARRAY tenant_tables LOOP',
    '    EXECUTE format(\'ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;\', tbl);',
    '    EXECUTE format(\'ALTER TABLE public.%I FORCE ROW LEVEL SECURITY;\', tbl);',
    "    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON public.%I;', tbl);",
    "    EXECUTE format('DROP POLICY IF EXISTS service_role_bypass ON public.%I;', tbl);",
    '    EXECUTE format($pol$',
    '      CREATE POLICY tenant_isolation ON public.%I',
    '      FOR ALL',
    `      USING (tenant_id = ${TENANT_GUC})`,
    `      WITH CHECK (tenant_id = ${TENANT_GUC});`,
    '    $pol$, tbl);',
    '    EXECUTE format($pol$',
    '      CREATE POLICY service_role_bypass ON public.%I',
    '      FOR ALL',
    `      USING (${SERVICE_ROLE_GUC} = 'true')`,
    `      WITH CHECK (${SERVICE_ROLE_GUC} = 'true');`,
    '    $pol$, tbl);',
    "    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN",
    "      EXECUTE format('REVOKE ALL ON public.%I FROM anon;', tbl);",
    '    END IF;',
    '  END LOOP;',
    'END',
    '$ddlguard_rls$;',
  ].join('\n');
}

/**
 * Verify that a (raw, un-tokenized) migration blob's FORCE-RLS coverage
 * is the guard-emitted canonical block and NOTHING ELSE. The author can
 * neither ship a table without RLS, swap the canonical GUC for a weaker
 * one, NOR supply their own policy (e.g. a wide-open `USING (true)`).
 *
 * This is a PER-TABLE guarantee, not a global one: the earlier global
 * `/CREATE POLICY tenant_isolation/.test(sql)` form let a second table
 * carry `ENABLE+FORCE` with ZERO policies (or a `USING (true)`) yet pass
 * because SOME other table's block contained the policy keyword. The
 * checks below bind every requirement to the canonical block that
 * actually lists the table.
 *
 * Verification (strongest acceptable form):
 *   1. Global GUC sanity — no legacy helper / foreign setting name.
 *   2. The ONLY row-security surface for spawned tables is the canonical
 *      guard block: every `CREATE POLICY`, `ENABLE/FORCE ROW LEVEL
 *      SECURITY`, and `USING (…)` must live inside the canonical DO
 *      `$ddlguard_rls$` block. An author-supplied policy outside it (a
 *      non-canonical name, a `USING (true)`, a wide-open bypass) is
 *      rejected.
 *   3. Per spawned table: it must be a literal member of the canonical
 *      block's `tenant_tables` ARRAY, and that block must carry the
 *      parameterised ENABLE + FORCE + a `tenant_isolation` policy whose
 *      USING is EXACTLY `tenant_id = current_setting(
 *      'app.current_tenant_id', true)` + a `service_role_bypass` policy
 *      bound to `app.is_service_role`.
 *   4. When `tenantId` is supplied (the real call site always supplies
 *      it) the block is BYTE-COMPARED against `buildCanonicalRlsBlock(
 *      tenantId, tables)` so an author can never hand-roll a block that
 *      merely passes the structural probes.
 */
export function verifyRlsForced(
  migrationSql: string,
  tenantNamespacedTables: ReadonlyArray<string>,
  tenantId?: string,
): RlsVerifyResult {
  const errors: string[] = [];
  const sql = migrationSql;

  // ── 1. Global GUC sanity ───────────────────────────────────────────
  if (/current_app_tenant_id\s*\(/i.test(sql)) {
    errors.push(
      'non-canonical GUC: public.current_app_tenant_id() is not permitted in spawned RLS (use app.current_tenant_id)',
    );
  }
  const settingNames = [...sql.matchAll(/current_setting\(\s*'([^']+)'/gi)].map(
    (m) => m[1],
  );
  for (const name of settingNames) {
    if (name !== 'app.current_tenant_id' && name !== 'app.is_service_role') {
      errors.push(`non-canonical GUC in spawned RLS: app setting '${name}'`);
    }
  }

  const bareTables = tenantNamespacedTables.map((t) => stripSchemaQualifier(t));

  // ── 2. Locate the single canonical guard block; it is the ONLY place
  // row-security may be manipulated for spawned tables. ───────────────
  const blocks = extractGuardBlocks(sql);
  if (blocks.length === 0) {
    errors.push(
      'missing the canonical guard FORCE-RLS block (DO $ddlguard_rls$ … $ddlguard_rls$)',
    );
  }
  if (blocks.length > 1) {
    errors.push(
      `expected exactly one canonical guard RLS block, found ${blocks.length}`,
    );
  }
  const block = blocks[0] ?? '';
  const outside = blocks.length === 1 ? sql.split(block).join(' ') : sql;

  // No row-security surface may exist OUTSIDE the canonical block — a
  // hand-rolled ENABLE/FORCE/CREATE POLICY/USING/REVOKE-from-RLS would
  // be an author trying to supply their own (weaker) policy.
  if (/CREATE\s+POLICY\b/i.test(outside)) {
    errors.push(
      'author-supplied CREATE POLICY outside the canonical guard block is forbidden',
    );
  }
  if (
    /\bENABLE\s+ROW\s+LEVEL\s+SECURITY/i.test(outside) ||
    /\bFORCE\s+ROW\s+LEVEL\s+SECURITY/i.test(outside)
  ) {
    errors.push(
      'ENABLE/FORCE ROW LEVEL SECURITY outside the canonical guard block is forbidden',
    );
  }
  if (/\bUSING\s*\(/i.test(outside)) {
    errors.push('a row-security USING (…) clause outside the canonical guard block is forbidden');
  }

  // ── 4. Strongest form: byte-compare the located block against the
  // freshly-built canonical block when tenantId is known. ─────────────
  if (blocks.length === 1 && tenantId !== undefined && errors.length === 0) {
    let canonicalDoBlock: string | null = null;
    try {
      // `buildCanonicalRlsBlock` prepends a comment header before the DO
      // block; compare only the DO-block portion of each so the leading
      // comment text is not part of the structural identity.
      const built = buildCanonicalRlsBlock(tenantId, bareTables);
      canonicalDoBlock = extractGuardBlocks(built)[0] ?? null;
    } catch (e) {
      errors.push(`cannot build canonical RLS block: ${(e as Error).message}`);
    }
    if (
      canonicalDoBlock !== null &&
      normaliseBlock(block) !== normaliseBlock(canonicalDoBlock)
    ) {
      errors.push(
        'spawned-table RLS does not byte-match the canonical guard block (author-modified RLS is forbidden)',
      );
    }
  }

  // ── 3. Per-table structural verification against the located block.
  // (Always runs — it is the only guarantee when tenantId is absent, and
  // a defence-in-depth cross-check when it is present.) ────────────────
  const blockHasEnable = /ENABLE\s+ROW\s+LEVEL\s+SECURITY/i.test(block);
  const blockHasForce = /FORCE\s+ROW\s+LEVEL\s+SECURITY/i.test(block);
  const blockHasCanonicalTenantPolicy = hasCanonicalTenantPolicy(block);
  const blockHasCanonicalServicePolicy = hasCanonicalServicePolicy(block);
  const blockIsForeach = /FOREACH\s+\w+\s+IN\s+ARRAY/i.test(block);

  for (const t of bareTables) {
    const listedInArray = new RegExp(`'\\s*${escapeRegex(t)}\\s*'`).test(block);
    if (!listedInArray) {
      errors.push(`canonical RLS block does not cover spawned table: ${t}`);
      continue;
    }
    if (!blockIsForeach) {
      errors.push(`table ${t}: RLS block is not the canonical FOREACH-array form`);
    }
    if (!blockHasEnable) errors.push(`table ${t}: missing ENABLE ROW LEVEL SECURITY`);
    if (!blockHasForce) errors.push(`table ${t}: missing FORCE ROW LEVEL SECURITY`);
    if (!blockHasCanonicalTenantPolicy)
      errors.push(
        `table ${t}: missing a tenant_isolation policy with the canonical USING (tenant_id = ${TENANT_GUC})`,
      );
    if (!blockHasCanonicalServicePolicy)
      errors.push(`table ${t}: missing a canonical service_role_bypass policy`);
  }

  return Object.freeze({
    ok: errors.length === 0,
    errors: Object.freeze([...new Set(errors)]),
  });
}

/**
 * Extract the body+delimiters of every canonical guard RLS block
 * (`DO $ddlguard_rls$ … $ddlguard_rls$`) found in the migration. The tag
 * is fixed by `buildCanonicalRlsBlock`, so any DO block with a different
 * tag is NOT a guard block and is handled elsewhere (the allowlist's
 * DO-block classifier). Returns the full `DO …;`-or-block substrings.
 */
function extractGuardBlocks(sql: string): string[] {
  const out: string[] = [];
  const tag = '$ddlguard_rls$';
  let from = 0;
  for (;;) {
    const doAt = sql.indexOf('DO ' + tag, from);
    if (doAt === -1) break;
    const bodyStart = doAt + ('DO ' + tag).length;
    const close = sql.indexOf(tag, bodyStart);
    if (close === -1) break; // unterminated → no complete block
    let end = close + tag.length;
    if (sql[end] === ';') end += 1; // include the closing statement `;`
    out.push(sql.slice(doAt, end));
    from = end;
  }
  return out;
}

/**
 * True when the block contains a `tenant_isolation` policy whose USING
 * (and WITH CHECK) clause is EXACTLY the canonical
 * `tenant_id = current_setting('app.current_tenant_id', true)`. A
 * `USING (true)`, a foreign-GUC USING, or any other predicate fails.
 */
function hasCanonicalTenantPolicy(block: string): boolean {
  if (!/CREATE\s+POLICY\s+tenant_isolation\b/i.test(block)) return false;
  // Reject a wide-open or non-canonical tenant_isolation predicate.
  return (
    block.includes(`USING (tenant_id = ${TENANT_GUC})`) &&
    block.includes(`WITH CHECK (tenant_id = ${TENANT_GUC})`)
  );
}

/**
 * True when the block contains a `service_role_bypass` policy bound to
 * the canonical `app.is_service_role` GUC.
 */
function hasCanonicalServicePolicy(block: string): boolean {
  if (!/CREATE\s+POLICY\s+service_role_bypass\b/i.test(block)) return false;
  return (
    block.includes(`USING (${SERVICE_ROLE_GUC} = 'true')`) &&
    block.includes(`WITH CHECK (${SERVICE_ROLE_GUC} = 'true')`)
  );
}

/** Collapse insignificant whitespace for a structural byte-compare. */
function normaliseBlock(block: string): string {
  return block.replace(/\s+/g, ' ').trim();
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
