/**
 * Mining-domain Swahili-English glossary seed (Wave 19H).
 *
 * 50+ entries spanning the Tume ya Madini licensing taxonomy, TRA tax
 * + royalty terminology, NEMC environmental compliance vocabulary, and
 * field-level operational language. Every entry cites its source.
 *
 * Primary sources cited inline per entry:
 *   - Tume ya Madini official website
 *     https://www.tumemadini.go.tz/ (accessed 2026-05-26)
 *   - Mineral Royalties and Inspection Fee Rates (Tumemadini)
 *     https://www.tumemadini.go.tz/pages/mineral-royalties-and-inspection-fees-rates/
 *     (accessed 2026-05-26)
 *   - Mining (Mineral Rights) Regulations — GN. No. 1 (Ministry of Minerals)
 *     https://www.madini.go.tz/media/GN_MINERAL_RIGHTS-REGULATIONS-C_6__CHAPA_GN._1.pdf
 *     (accessed 2026-05-26)
 *   - The Mining Act, Cap.123 (consolidated to 2025)
 *     https://www.tumemadini.go.tz/media/uploads/publications/2025/06/29/The_Mining_Act.pdf
 *     (accessed 2026-05-26)
 *   - Ministry of Minerals — Republic of Tanzania
 *     https://www.madini.go.tz/ (accessed 2026-05-26)
 *   - Clyde & Co — "Tanzania Enacts the Mining (Technical Support to Small
 *     Scale Miners) Regulations, 2025"
 *     https://www.clydeco.com/en/insights/2025/05/tanzania-enacts-mining-technical-support
 *     (accessed 2026-05-26)
 */

import type { SwahiliTerm } from '../types.js';

const TUMEMADINI: SwahiliTerm['citation'] = Object.freeze({
  url: 'https://www.tumemadini.go.tz/',
  title: 'TUME YA MADINI — Official Website',
  accessedAt: '2026-05-26',
});

const TUMEMADINI_ROYALTY: SwahiliTerm['citation'] = Object.freeze({
  url: 'https://www.tumemadini.go.tz/pages/mineral-royalties-and-inspection-fees-rates/',
  title: 'Mineral Royalties and Inspection Fee Rates — Tume ya Madini',
  accessedAt: '2026-05-26',
});

const MADINI_REGS: SwahiliTerm['citation'] = Object.freeze({
  url: 'https://www.madini.go.tz/media/GN_MINERAL_RIGHTS-REGULATIONS-C_6__CHAPA_GN._1.pdf',
  title: 'Mining (Mineral Rights) Regulations — GN. No. 1',
  accessedAt: '2026-05-26',
});

const MINING_ACT: SwahiliTerm['citation'] = Object.freeze({
  url: 'https://www.tumemadini.go.tz/media/uploads/publications/2025/06/29/The_Mining_Act.pdf',
  title: 'The Mining Act, Cap.123',
  accessedAt: '2026-05-26',
});

const MADINI_MIN: SwahiliTerm['citation'] = Object.freeze({
  url: 'https://www.madini.go.tz/',
  title: 'Ministry of Minerals — Republic of Tanzania',
  accessedAt: '2026-05-26',
});

const CLYDECO_2025: SwahiliTerm['citation'] = Object.freeze({
  url: 'https://www.clydeco.com/en/insights/2025/05/tanzania-enacts-mining-technical-support',
  title: 'Tanzania Enacts the Mining (Technical Support to Small Scale Miners) Regulations, 2025',
  accessedAt: '2026-05-26',
});

/**
 * The seed glossary. Entries are frozen on construction.
 */
export const MINING_TERMS_SEED: ReadonlyArray<SwahiliTerm> = Object.freeze([
  // -------- Core regulators -----------------------------------------------
  Object.freeze({
    term: 'Tume ya Madini',
    lemma: 'Tume ya Madini',
    nounClass: 9,
    pluralClass: null,
    register: 'formal',
    domain: 'regulator',
    enEquivalent: 'Mining Commission',
    definition: Object.freeze({
      sw: 'Taasisi ya serikali inayoidhinisha leseni za madini Tanzania.',
      en: 'Statutory body that issues and regulates mining licences in Tanzania.',
    }),
    citation: TUMEMADINI,
  }),
  Object.freeze({
    term: 'Wizara ya Madini',
    lemma: 'Wizara ya Madini',
    nounClass: 9,
    pluralClass: null,
    register: 'formal',
    domain: 'regulator',
    enEquivalent: 'Ministry of Minerals',
    definition: Object.freeze({
      sw: 'Wizara ya serikali ya Tanzania inayohusika na sekta ya madini.',
      en: 'Government ministry responsible for the minerals sector.',
    }),
    citation: MADINI_MIN,
  }),
  Object.freeze({
    term: 'NEMC',
    lemma: 'NEMC',
    nounClass: 9,
    pluralClass: null,
    register: 'formal',
    domain: 'regulator',
    enEquivalent: 'National Environment Management Council',
    definition: Object.freeze({
      sw: 'Baraza la usimamizi wa mazingira Tanzania.',
      en: 'Tanzanian environmental regulator.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'TRA',
    lemma: 'TRA',
    nounClass: 9,
    pluralClass: null,
    register: 'formal',
    domain: 'regulator',
    enEquivalent: 'Tanzania Revenue Authority',
    definition: Object.freeze({
      sw: 'Mamlaka ya Mapato Tanzania.',
      en: 'Tax authority collecting royalties and inspection fees.',
    }),
    citation: TUMEMADINI_ROYALTY,
  }),
  // -------- Licensing -----------------------------------------------------
  Object.freeze({
    term: 'leseni ya uchimbaji mdogo',
    lemma: 'leseni',
    nounClass: 9,
    pluralClass: 10,
    register: 'formal',
    domain: 'licensing',
    enEquivalent: 'Primary Mining Licence (PML)',
    definition: Object.freeze({
      sw: 'Leseni ya uchimbaji mdogo inayotolewa kwa kipindi kisichozidi miaka saba.',
      en: 'Small-scale mining licence issued for up to seven years.',
    }),
    citation: MADINI_REGS,
  }),
  Object.freeze({
    term: 'leseni ya uchimbaji wa kati',
    lemma: 'leseni',
    nounClass: 9,
    pluralClass: 10,
    register: 'formal',
    domain: 'licensing',
    enEquivalent: 'Medium-scale Mining Licence (ML)',
    definition: Object.freeze({
      sw: 'Leseni ya uchimbaji wa kati inayotolewa kwa kipindi kisichozidi miaka kumi.',
      en: 'Medium-scale mining licence issued for up to ten years.',
    }),
    citation: MADINI_REGS,
  }),
  Object.freeze({
    term: 'leseni ya uchimbaji mkubwa',
    lemma: 'leseni',
    nounClass: 9,
    pluralClass: 10,
    register: 'formal',
    domain: 'licensing',
    enEquivalent: 'Special Mining Licence (SML)',
    definition: Object.freeze({
      sw: 'Leseni ya uchimbaji mkubwa kwa miradi yenye uwekezaji mkubwa.',
      en: 'Large-scale mining licence for large-capex projects.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'leseni ya utafutaji',
    lemma: 'leseni',
    nounClass: 9,
    pluralClass: 10,
    register: 'formal',
    domain: 'licensing',
    enEquivalent: 'Prospecting Licence (PL)',
    definition: Object.freeze({
      sw: 'Leseni ya utafutaji wa madini, isiyozidi miaka minne.',
      en: 'Prospecting licence; up to four years.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'kibali cha uchimbaji',
    lemma: 'kibali',
    nounClass: 7,
    pluralClass: 8,
    register: 'formal',
    domain: 'licensing',
    enEquivalent: 'mining permit',
    definition: Object.freeze({
      sw: 'Hati maalum inayoruhusu uchimbaji wa madini katika eneo lililoteuliwa.',
      en: 'Authorisation permitting mining in a designated area.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'kibali cha biashara',
    lemma: 'kibali',
    nounClass: 7,
    pluralClass: 8,
    register: 'formal',
    domain: 'licensing',
    enEquivalent: 'dealer licence',
    definition: Object.freeze({
      sw: 'Kibali cha kufanya biashara ya madini.',
      en: 'Licence to trade in minerals.',
    }),
    citation: MADINI_REGS,
  }),
  Object.freeze({
    term: 'kibali cha uchakataji',
    lemma: 'kibali',
    nounClass: 7,
    pluralClass: 8,
    register: 'formal',
    domain: 'licensing',
    enEquivalent: 'processing permit',
    definition: Object.freeze({
      sw: 'Kibali cha uchakataji wa madini.',
      en: 'Permit for mineral processing.',
    }),
    citation: MADINI_REGS,
  }),
  // -------- Tax / royalty -------------------------------------------------
  Object.freeze({
    term: 'mrabaha',
    lemma: 'mrabaha',
    nounClass: 3,
    pluralClass: 4,
    register: 'formal',
    domain: 'royalty',
    enEquivalent: 'royalty',
    definition: Object.freeze({
      sw: 'Malipo kwa serikali kutokana na thamani ya madini.',
      en: 'Payment to government based on the gross value of minerals.',
    }),
    citation: TUMEMADINI_ROYALTY,
  }),
  Object.freeze({
    term: 'ada ya ukaguzi',
    lemma: 'ada',
    nounClass: 9,
    pluralClass: 10,
    register: 'formal',
    domain: 'royalty',
    enEquivalent: 'inspection fee',
    definition: Object.freeze({
      sw: 'Tozo ya ukaguzi inayolipwa pamoja na mrabaha.',
      en: 'Inspection fee charged alongside royalty.',
    }),
    citation: TUMEMADINI_ROYALTY,
  }),
  Object.freeze({
    term: 'thamani ya jumla',
    lemma: 'thamani',
    nounClass: 9,
    pluralClass: 10,
    register: 'formal',
    domain: 'royalty',
    enEquivalent: 'gross value',
    definition: Object.freeze({
      sw: 'Thamani ya soko ya madini iliyobainishwa.',
      en: 'Determined market value of minerals.',
    }),
    citation: TUMEMADINI_ROYALTY,
  }),
  Object.freeze({
    term: 'kodi',
    lemma: 'kodi',
    nounClass: 9,
    pluralClass: 10,
    register: 'formal',
    domain: 'tax',
    enEquivalent: 'tax',
    definition: Object.freeze({
      sw: 'Malipo ya lazima kwa serikali.',
      en: 'Mandatory tax payment.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'ushuru',
    lemma: 'ushuru',
    nounClass: 11,
    pluralClass: 10,
    register: 'formal',
    domain: 'tax',
    enEquivalent: 'duty / levy',
    definition: Object.freeze({
      sw: 'Tozo / ushuru wa serikali, ukijumuisha ule wa forodha.',
      en: 'Government levy including customs duty.',
    }),
    citation: MINING_ACT,
  }),
  // -------- Minerals (core terms) -----------------------------------------
  Object.freeze({
    term: 'madini',
    lemma: 'madini',
    nounClass: 6,
    pluralClass: null,
    register: 'formal',
    domain: 'core',
    enEquivalent: 'minerals',
    definition: Object.freeze({
      sw: 'Vitu vya thamani vinavyochimbwa ardhini.',
      en: 'Mined substances of value.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'dhahabu',
    lemma: 'dhahabu',
    nounClass: 9,
    pluralClass: null,
    register: 'formal',
    domain: 'core',
    enEquivalent: 'gold',
    definition: Object.freeze({
      sw: 'Madini ya thamani ya rangi ya manjano.',
      en: 'Precious yellow metal.',
    }),
    citation: TUMEMADINI_ROYALTY,
  }),
  Object.freeze({
    term: 'almasi',
    lemma: 'almasi',
    nounClass: 9,
    pluralClass: 10,
    register: 'formal',
    domain: 'core',
    enEquivalent: 'diamond',
    definition: Object.freeze({
      sw: 'Jiwe la thamani.',
      en: 'Precious gemstone.',
    }),
    citation: TUMEMADINI_ROYALTY,
  }),
  Object.freeze({
    term: 'shaba',
    lemma: 'shaba',
    nounClass: 9,
    pluralClass: null,
    register: 'formal',
    domain: 'core',
    enEquivalent: 'copper',
    definition: Object.freeze({
      sw: 'Madini ya shaba.',
      en: 'Copper.',
    }),
    citation: TUMEMADINI_ROYALTY,
  }),
  Object.freeze({
    term: 'chuma',
    lemma: 'chuma',
    nounClass: 7,
    pluralClass: 8,
    register: 'formal',
    domain: 'core',
    enEquivalent: 'iron',
    definition: Object.freeze({
      sw: 'Madini ya chuma.',
      en: 'Iron / iron ore.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'tanzanite',
    lemma: 'tanzanite',
    nounClass: 9,
    pluralClass: null,
    register: 'formal',
    domain: 'core',
    enEquivalent: 'tanzanite',
    definition: Object.freeze({
      sw: 'Jiwe la thamani la kipekee Tanzania.',
      en: 'Gemstone unique to Tanzania.',
    }),
    citation: TUMEMADINI_ROYALTY,
  }),
  Object.freeze({
    term: 'makaa ya mawe',
    lemma: 'makaa',
    nounClass: 6,
    pluralClass: null,
    register: 'formal',
    domain: 'core',
    enEquivalent: 'coal',
    definition: Object.freeze({
      sw: 'Madini ya makaa ya mawe.',
      en: 'Coal.',
    }),
    citation: TUMEMADINI_ROYALTY,
  }),
  // -------- Operations ----------------------------------------------------
  Object.freeze({
    term: 'uchimbaji',
    lemma: 'uchimbaji',
    nounClass: 11,
    pluralClass: null,
    register: 'formal',
    domain: 'operations',
    enEquivalent: 'mining',
    definition: Object.freeze({
      sw: 'Tendo la kuchimba madini.',
      en: 'The act of mining.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'uchimbaji mdogo',
    lemma: 'uchimbaji',
    nounClass: 11,
    pluralClass: null,
    register: 'formal',
    domain: 'operations',
    enEquivalent: 'small-scale mining',
    definition: Object.freeze({
      sw: 'Uchimbaji wa kiwango kidogo.',
      en: 'Small-scale mining operations.',
    }),
    citation: CLYDECO_2025,
  }),
  Object.freeze({
    term: 'uchimbaji wa kati',
    lemma: 'uchimbaji',
    nounClass: 11,
    pluralClass: null,
    register: 'formal',
    domain: 'operations',
    enEquivalent: 'medium-scale mining',
    definition: Object.freeze({
      sw: 'Uchimbaji wa kiwango cha kati.',
      en: 'Medium-scale mining operations.',
    }),
    citation: MADINI_REGS,
  }),
  Object.freeze({
    term: 'utafutaji',
    lemma: 'utafutaji',
    nounClass: 11,
    pluralClass: null,
    register: 'formal',
    domain: 'operations',
    enEquivalent: 'prospecting / exploration',
    definition: Object.freeze({
      sw: 'Utafutaji wa madini ardhini.',
      en: 'Mineral exploration.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'mgodi',
    lemma: 'mgodi',
    nounClass: 3,
    pluralClass: 4,
    register: 'formal',
    domain: 'operations',
    enEquivalent: 'mine',
    definition: Object.freeze({
      sw: 'Eneo la uchimbaji wa madini.',
      en: 'Mine site.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'mchimbaji',
    lemma: 'mchimbaji',
    nounClass: 1,
    pluralClass: 2,
    register: 'formal',
    domain: 'operations',
    enEquivalent: 'miner',
    definition: Object.freeze({
      sw: 'Mtu anayechimba madini.',
      en: 'A person who mines minerals.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'wachimbaji wadogo',
    lemma: 'mchimbaji',
    nounClass: 2,
    pluralClass: null,
    register: 'formal',
    domain: 'operations',
    enEquivalent: 'small-scale miners',
    definition: Object.freeze({
      sw: 'Wachimbaji wa madini kwa kiwango kidogo.',
      en: 'Small-scale miners.',
    }),
    citation: CLYDECO_2025,
  }),
  Object.freeze({
    term: 'kitalu',
    lemma: 'kitalu',
    nounClass: 7,
    pluralClass: 8,
    register: 'formal',
    domain: 'operations',
    enEquivalent: 'mining block / parcel',
    definition: Object.freeze({
      sw: 'Eneo lililochaguliwa kwa uchimbaji.',
      en: 'Designated mining block.',
    }),
    citation: MADINI_REGS,
  }),
  Object.freeze({
    term: 'shimo',
    lemma: 'shimo',
    nounClass: 5,
    pluralClass: 6,
    register: 'formal',
    domain: 'operations',
    enEquivalent: 'pit',
    definition: Object.freeze({
      sw: 'Shimo la uchimbaji wa madini.',
      en: 'Pit / hole used for mining.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'kina',
    lemma: 'kina',
    nounClass: 7,
    pluralClass: 8,
    register: 'formal',
    domain: 'operations',
    enEquivalent: 'depth',
    definition: Object.freeze({
      sw: 'Urefu wa shimo kuelekea ndani ya ardhi.',
      en: 'Depth measurement of a mining shaft.',
    }),
    citation: MINING_ACT,
  }),
  // -------- Trade --------------------------------------------------------
  Object.freeze({
    term: 'parseli',
    lemma: 'parseli',
    nounClass: 9,
    pluralClass: 10,
    register: 'formal',
    domain: 'trade',
    enEquivalent: 'parcel',
    definition: Object.freeze({
      sw: 'Kifurushi cha madini kinachouzwa.',
      en: 'Parcel of minerals for sale.',
    }),
    citation: TUMEMADINI,
  }),
  Object.freeze({
    term: 'forodha',
    lemma: 'forodha',
    nounClass: 9,
    pluralClass: 10,
    register: 'formal',
    domain: 'trade',
    enEquivalent: 'customs',
    definition: Object.freeze({
      sw: 'Mamlaka ya kushughulikia mizigo inayoingia / kutoka.',
      en: 'Customs authority handling imports / exports.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'bandari',
    lemma: 'bandari',
    nounClass: 9,
    pluralClass: 10,
    register: 'formal',
    domain: 'trade',
    enEquivalent: 'port',
    definition: Object.freeze({
      sw: 'Eneo la bandarini la kuingiza / kutoa mizigo.',
      en: 'Port for cargo handling.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'soko la madini',
    lemma: 'soko',
    nounClass: 5,
    pluralClass: 6,
    register: 'formal',
    domain: 'trade',
    enEquivalent: 'mineral market',
    definition: Object.freeze({
      sw: 'Eneo rasmi la mauzo ya madini.',
      en: 'Official mineral trading market.',
    }),
    citation: TUMEMADINI,
  }),
  Object.freeze({
    term: 'muuzaji',
    lemma: 'muuzaji',
    nounClass: 1,
    pluralClass: 2,
    register: 'formal',
    domain: 'trade',
    enEquivalent: 'seller / dealer',
    definition: Object.freeze({
      sw: 'Mtu anayeuza madini.',
      en: 'Person who sells minerals.',
    }),
    citation: MADINI_REGS,
  }),
  Object.freeze({
    term: 'mnunuzi',
    lemma: 'mnunuzi',
    nounClass: 1,
    pluralClass: 2,
    register: 'formal',
    domain: 'trade',
    enEquivalent: 'buyer',
    definition: Object.freeze({
      sw: 'Mtu anayenunua madini.',
      en: 'Person who buys minerals.',
    }),
    citation: MADINI_REGS,
  }),
  Object.freeze({
    term: 'gramu',
    lemma: 'gramu',
    nounClass: 9,
    pluralClass: 10,
    register: 'formal',
    domain: 'trade',
    enEquivalent: 'gram',
    definition: Object.freeze({
      sw: 'Kipimo cha uzito (gramu moja).',
      en: 'Weight unit (one gram).',
    }),
    citation: TUMEMADINI_ROYALTY,
  }),
  // -------- Governance + admin -------------------------------------------
  Object.freeze({
    term: 'baraza la wachimbaji',
    lemma: 'baraza',
    nounClass: 5,
    pluralClass: 6,
    register: 'formal',
    domain: 'governance',
    enEquivalent: 'miners cooperative council',
    definition: Object.freeze({
      sw: 'Baraza la wawakilishi wa wachimbaji.',
      en: 'Council representing miners.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'mwenyekiti',
    lemma: 'mwenyekiti',
    nounClass: 1,
    pluralClass: 2,
    register: 'formal',
    domain: 'governance',
    enEquivalent: 'chairperson',
    definition: Object.freeze({
      sw: 'Kiongozi anayeongoza mkutano au baraza.',
      en: 'Chair of a council or meeting.',
    }),
    citation: MADINI_REGS,
  }),
  Object.freeze({
    term: 'katibu',
    lemma: 'katibu',
    nounClass: 1,
    pluralClass: 2,
    register: 'formal',
    domain: 'governance',
    enEquivalent: 'secretary',
    definition: Object.freeze({
      sw: 'Mwandishi rasmi wa taarifa za mkutano.',
      en: 'Official secretary of meetings.',
    }),
    citation: MADINI_REGS,
  }),
  Object.freeze({
    term: 'mratibu',
    lemma: 'mratibu',
    nounClass: 1,
    pluralClass: 2,
    register: 'formal',
    domain: 'governance',
    enEquivalent: 'coordinator',
    definition: Object.freeze({
      sw: 'Mtu anayeratibu shughuli za uchimbaji.',
      en: 'Coordinator of mining activities.',
    }),
    citation: CLYDECO_2025,
  }),
  Object.freeze({
    term: 'wakala',
    lemma: 'wakala',
    nounClass: 1,
    pluralClass: 2,
    register: 'formal',
    domain: 'governance',
    enEquivalent: 'agent',
    definition: Object.freeze({
      sw: 'Mtu aliyepewa mamlaka ya kufanya kazi kwa niaba ya mwingine.',
      en: 'Authorised agent acting on behalf of another.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'mwekezaji',
    lemma: 'mwekezaji',
    nounClass: 1,
    pluralClass: 2,
    register: 'formal',
    domain: 'governance',
    enEquivalent: 'investor',
    definition: Object.freeze({
      sw: 'Mtu anayeweka mtaji kwenye mradi.',
      en: 'Person investing capital in a project.',
    }),
    citation: MINING_ACT,
  }),
  // -------- Environment / compliance --------------------------------------
  Object.freeze({
    term: 'mazingira',
    lemma: 'mazingira',
    nounClass: 6,
    pluralClass: null,
    register: 'formal',
    domain: 'environment',
    enEquivalent: 'environment',
    definition: Object.freeze({
      sw: 'Mazingira ya asili na yaliyojengwa.',
      en: 'Natural and built environment.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'uchafuzi',
    lemma: 'uchafuzi',
    nounClass: 11,
    pluralClass: null,
    register: 'formal',
    domain: 'environment',
    enEquivalent: 'pollution',
    definition: Object.freeze({
      sw: 'Uharibifu wa mazingira.',
      en: 'Environmental contamination.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'ukarabati wa ardhi',
    lemma: 'ukarabati',
    nounClass: 11,
    pluralClass: null,
    register: 'formal',
    domain: 'environment',
    enEquivalent: 'land rehabilitation',
    definition: Object.freeze({
      sw: 'Kurudisha ardhi kwenye hali yake ya awali baada ya uchimbaji.',
      en: 'Post-mining land rehabilitation.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'tathmini ya athari za mazingira',
    lemma: 'tathmini',
    nounClass: 9,
    pluralClass: 10,
    register: 'formal',
    domain: 'environment',
    enEquivalent: 'environmental impact assessment',
    definition: Object.freeze({
      sw: 'Uchunguzi wa madhara yanayoweza kutokea mazingirani.',
      en: 'Environmental impact assessment (EIA).',
    }),
    citation: MINING_ACT,
  }),
  // -------- Compliance + reporting ----------------------------------------
  Object.freeze({
    term: 'taarifa ya uzalishaji',
    lemma: 'taarifa',
    nounClass: 9,
    pluralClass: 10,
    register: 'formal',
    domain: 'compliance',
    enEquivalent: 'production report',
    definition: Object.freeze({
      sw: 'Ripoti ya uzalishaji wa madini kwa kipindi fulani.',
      en: 'Production report for a given period.',
    }),
    citation: TUMEMADINI,
  }),
  Object.freeze({
    term: 'uthibitisho wa malipo',
    lemma: 'uthibitisho',
    nounClass: 11,
    pluralClass: null,
    register: 'formal',
    domain: 'compliance',
    enEquivalent: 'payment confirmation',
    definition: Object.freeze({
      sw: 'Hati inayothibitisha malipo kwa serikali.',
      en: 'Receipt of payment to government.',
    }),
    citation: TUMEMADINI_ROYALTY,
  }),
  Object.freeze({
    term: 'cheti',
    lemma: 'cheti',
    nounClass: 7,
    pluralClass: 8,
    register: 'formal',
    domain: 'compliance',
    enEquivalent: 'certificate',
    definition: Object.freeze({
      sw: 'Hati rasmi ya uthibitisho.',
      en: 'Official certificate.',
    }),
    citation: MADINI_REGS,
  }),
  Object.freeze({
    term: 'hati ya mauzo',
    lemma: 'hati',
    nounClass: 9,
    pluralClass: 10,
    register: 'formal',
    domain: 'compliance',
    enEquivalent: 'bill of sale',
    definition: Object.freeze({
      sw: 'Hati inayothibitisha uuzaji wa madini.',
      en: 'Bill of sale evidencing mineral disposal.',
    }),
    citation: MADINI_REGS,
  }),
  Object.freeze({
    term: 'kibali cha kusafirisha',
    lemma: 'kibali',
    nounClass: 7,
    pluralClass: 8,
    register: 'formal',
    domain: 'compliance',
    enEquivalent: 'export permit',
    definition: Object.freeze({
      sw: 'Kibali cha kusafirisha madini nje ya nchi.',
      en: 'Permit for exporting minerals.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'eneo la uchimbaji',
    lemma: 'eneo',
    nounClass: 5,
    pluralClass: 6,
    register: 'formal',
    domain: 'operations',
    enEquivalent: 'mining area',
    definition: Object.freeze({
      sw: 'Sehemu iliyotengwa kwa shughuli za uchimbaji.',
      en: 'Designated mining area.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'uchimbaji haramu',
    lemma: 'uchimbaji',
    nounClass: 11,
    pluralClass: null,
    register: 'formal',
    domain: 'compliance',
    enEquivalent: 'illegal mining',
    definition: Object.freeze({
      sw: 'Uchimbaji bila kibali rasmi.',
      en: 'Mining conducted without lawful authorisation.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'ukaguzi',
    lemma: 'ukaguzi',
    nounClass: 11,
    pluralClass: null,
    register: 'formal',
    domain: 'compliance',
    enEquivalent: 'inspection',
    definition: Object.freeze({
      sw: 'Uchunguzi rasmi wa shughuli za uchimbaji.',
      en: 'Official inspection of mining operations.',
    }),
    citation: TUMEMADINI_ROYALTY,
  }),
  Object.freeze({
    term: 'mkaguzi',
    lemma: 'mkaguzi',
    nounClass: 1,
    pluralClass: 2,
    register: 'formal',
    domain: 'compliance',
    enEquivalent: 'inspector',
    definition: Object.freeze({
      sw: 'Afisa anayefanya ukaguzi.',
      en: 'Mining inspection officer.',
    }),
    citation: TUMEMADINI_ROYALTY,
  }),
  Object.freeze({
    term: 'sheria',
    lemma: 'sheria',
    nounClass: 9,
    pluralClass: 10,
    register: 'formal',
    domain: 'core',
    enEquivalent: 'law',
    definition: Object.freeze({
      sw: 'Sheria zilizopitishwa na Bunge.',
      en: 'Statute passed by parliament.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'kanuni',
    lemma: 'kanuni',
    nounClass: 9,
    pluralClass: 10,
    register: 'formal',
    domain: 'core',
    enEquivalent: 'regulation',
    definition: Object.freeze({
      sw: 'Maelekezo yanayotungwa chini ya sheria.',
      en: 'Regulation issued under a statute.',
    }),
    citation: MADINI_REGS,
  }),
  Object.freeze({
    term: 'afisa madini mkazi',
    lemma: 'afisa madini',
    nounClass: 9,
    pluralClass: 10,
    register: 'formal',
    domain: 'governance',
    enEquivalent: 'Resident Mining Officer',
    definition: Object.freeze({
      sw: 'Afisa madini wa kanda mkazi.',
      en: 'Regional Resident Mining Officer.',
    }),
    citation: TUMEMADINI,
  }),
  Object.freeze({
    term: 'pesa',
    lemma: 'pesa',
    nounClass: 9,
    pluralClass: 10,
    register: 'colloquial',
    domain: 'trade',
    enEquivalent: 'money',
    definition: Object.freeze({
      sw: 'Fedha taslimu.',
      en: 'Money / cash.',
    }),
    citation: MINING_ACT,
  }),
  Object.freeze({
    term: 'fedha',
    lemma: 'fedha',
    nounClass: 9,
    pluralClass: 10,
    register: 'formal',
    domain: 'trade',
    enEquivalent: 'currency / money',
    definition: Object.freeze({
      sw: 'Fedha za serikali / sarafu.',
      en: 'Official currency.',
    }),
    citation: MINING_ACT,
  }),
]);
