#!/bin/sh
# =============================================================================
# bootstrap-secrets.sh — generate the [SELF-GEN] secrets into .env.local
# =============================================================================
# POSIX sh. Generates the cryptographic secrets the deploy owns (JWT, session
# hash-chain, webhook HMACs, the Ed25519 ledger-attestor key, the ledger role
# login passwords) with openssl, and APPENDS them to a gitignored .env.local.
#
# Guarantees:
#   * Idempotent     — a key already set (non-empty, non-placeholder) is SKIPPED.
#   * Non-destructive — existing values are NEVER overwritten; we only append.
#   * Quiet on secrets — generated VALUES are never printed to stdout. Only the
#                        key names that were written are reported.
#   * No tracked secret — values land only in .env.local, which is gitignored.
#
# This complements (does not replace) `pnpm gen-secrets`
# (scripts/generate-borjie-secrets.mjs), which covers the same JWT/session/
# internal secrets via Node. Use whichever your deploy host has; this sh
# version additionally mints the LITFIN-wave secrets (Ed25519 attestor key,
# Africa's-Talking webhook secret, ledger role passwords) and prints the
# [OPERATOR] paste-in checklist.
#
# Usage:
#   sh scripts/secrets/bootstrap-secrets.sh           # generate + report
#   ENV_FILE=.env.staging sh scripts/secrets/bootstrap-secrets.sh
#
# Canonical secrets manifest: scripts/secrets/REQUIRED_SECRETS.md
# =============================================================================

set -eu

# Resolve repo root from this script's location (scripts/secrets/ -> repo root).
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)
ENV_FILE_NAME=${ENV_FILE:-.env.local}
ENV_PATH="$REPO_ROOT/$ENV_FILE_NAME"

if ! command -v openssl >/dev/null 2>&1; then
  echo "fatal: openssl not found on PATH — required to generate secrets." >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Pre-flight: confirm the target env file is gitignored. We never want to
# write secrets into a tracked file. `git check-ignore` exits 0 when ignored.
# ---------------------------------------------------------------------------
if command -v git >/dev/null 2>&1 && git -C "$REPO_ROOT" rev-parse >/dev/null 2>&1; then
  if git -C "$REPO_ROOT" check-ignore -q "$ENV_FILE_NAME"; then
    : # ignored — good
  else
    echo "fatal: $ENV_FILE_NAME is NOT gitignored. Refusing to write secrets" >&2
    echo "       to a tracked file. Add '$ENV_FILE_NAME' to .gitignore first." >&2
    exit 1
  fi
fi

# Create the file if absent (touch is non-destructive if it exists).
if [ ! -f "$ENV_PATH" ]; then
  printf '# Local secrets — gitignored. Generated by scripts/secrets/bootstrap-secrets.sh\n' > "$ENV_PATH"
  printf '# %s\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$ENV_PATH"
fi

# ---------------------------------------------------------------------------
# Helpers.
# ---------------------------------------------------------------------------

# is_placeholder VALUE -> 0 (true) when the value is empty or a known stand-in.
is_placeholder() {
  case "$1" in
    "" ) return 0 ;;
    TODO_BORJIE_* | TODO_PRELAUNCH* | your-* | replace-me* | CHANGEME* | "<paste"* )
      return 0 ;;
    * ) return 1 ;;
  esac
}

# current_value KEY -> echoes the value currently set for KEY in $ENV_PATH
# (last assignment wins), or empty string when unset.
current_value() {
  key=$1
  # Match `KEY=...` allowing leading spaces; strip the `KEY=` prefix.
  line=$(grep -E "^[[:space:]]*${key}=" "$ENV_PATH" 2>/dev/null | tail -n 1 || true)
  [ -z "$line" ] && { printf '%s' ""; return; }
  printf '%s' "${line#*=}"
}

WRITTEN=""
SKIPPED=""

# set_secret KEY GENERATOR_CMD
# Appends `KEY=<generated>` only when KEY is unset/placeholder. The generated
# value is read into a variable and written to the file — never echoed.
set_secret() {
  key=$1
  gen=$2
  existing=$(current_value "$key")
  if is_placeholder "$existing"; then
    value=$(eval "$gen")
    # Append (never rewrite prior lines). The value never touches stdout.
    printf '%s=%s\n' "$key" "$value" >> "$ENV_PATH"
    WRITTEN="$WRITTEN $key"
  else
    SKIPPED="$SKIPPED $key"
  fi
}

# Ed25519 PEM flattened to a single line (literal \n) so it survives dotenv
# parsing. The attestor un-escapes \n before createPrivateKey.
gen_ed25519_pem_oneline() {
  openssl genpkey -algorithm ed25519 2>/dev/null | awk 'BEGIN{ORS="\\n"}{print}'
}

# ---------------------------------------------------------------------------
# [SELF-GEN] secrets. openssl rand for symmetric secrets; genpkey for the
# asymmetric attestor key.
# ---------------------------------------------------------------------------

# Auth / session (also covered by `pnpm gen-secrets`; harmless to share).
set_secret JWT_SECRET                'openssl rand -base64 48'
set_secret JWT_REFRESH_SECRET        'openssl rand -base64 48'
set_secret SESSION_HASH_SECRET       'openssl rand -base64 48'
set_secret AUDIT_TRAIL_SIGNING_SECRET 'openssl rand -base64 32'
set_secret COOKIE_SECRET             'openssl rand -base64 48'

# Encryption-at-rest + PII salt.
set_secret ENCRYPTION_MASTER_KEY     'openssl rand -base64 32'
set_secret USER_HASH_SALT            'openssl rand -base64 32'

# Internal + webhook HMAC secrets.
set_secret INTERNAL_API_KEY              'openssl rand -hex 32'
set_secret WEBHOOK_DEFAULT_HMAC_SECRET   'openssl rand -hex 32'

# LITFIN-wave secrets.
# Africa's-Talking inbound/delivery HMAC — must match the AT webhook config.
set_secret AFRICASTALKING_WEBHOOK_SECRET 'openssl rand -hex 32'
# Ledger attestor Ed25519 signing key (stable across restarts).
set_secret LEDGER_ATTEST_SIGNING_KEY_PEM 'gen_ed25519_pem_oneline'

# Ledger role login passwords. These are NOT consumed as env vars directly —
# the operator pastes them into `CREATE ROLE ... PASSWORD '...'` (migration
# 0275) AND into LEDGER_DATABASE_URL{,_READONLY}. We stash them in .env.local
# under helper keys so the operator can copy them without them ever hitting
# the terminal or a tracked file.
set_secret LEDGER_ENGINE_APP_PASSWORD 'openssl rand -base64 24'
set_secret LEDGER_READ_APP_PASSWORD   'openssl rand -base64 24'

# ---------------------------------------------------------------------------
# Report — names only, never values.
# ---------------------------------------------------------------------------
echo "bootstrap-secrets: target $ENV_FILE_NAME (gitignored)."
if [ -n "$WRITTEN" ]; then
  echo "  generated (values written to $ENV_FILE_NAME, not shown):"
  for k in $WRITTEN; do echo "    + $k"; done
else
  echo "  nothing to generate — all [SELF-GEN] keys already set (idempotent no-op)."
fi
if [ -n "$SKIPPED" ]; then
  echo "  preserved (already set):"
  for k in $SKIPPED; do echo "    = $k"; done
fi

cat <<CHECKLIST

---------------------------------------------------------------------------
[OPERATOR] keys you MUST paste by hand (cannot be generated) — fill these in
$ENV_FILE_NAME / your secret store before deploy. See
scripts/secrets/REQUIRED_SECRETS.md for where each is obtained.
---------------------------------------------------------------------------
  [ ] DATABASE_URL                  Supabase pooler URL (Dashboard > Database)
  [ ] SUPABASE_URL / *_ANON_KEY     Supabase Dashboard > Settings > API
  [ ] SUPABASE_SERVICE_ROLE_KEY     Supabase Dashboard > Settings > API (SERVER-ONLY)
  [ ] SUPABASE_JWT_SECRET           Supabase Dashboard > Settings > API > JWT
  [ ] ANTHROPIC_API_KEY             console.anthropic.com > API keys
  [ ] OPENAI_API_KEY                platform.openai.com > API keys
  [ ] REDIS_URL                     managed Redis/Upstash endpoint
  [ ] AFRICAS_TALKING_API_KEY       africastalking.com dashboard (+ USERNAME)
  [ ] M-Pesa / Daraja creds         Safaricom Daraja portal (if payments live)
  [ ] AWS_* + LEDGER_ATTEST_BUCKET  AWS console (only if S3 object-lock sink used)

Ledger role setup (run against the DB, then point the URLs at the roles):
  CREATE ROLE ledger_engine_app LOGIN PASSWORD '<LEDGER_ENGINE_APP_PASSWORD>';
  GRANT borjie_ledger_writer TO ledger_engine_app;
  CREATE ROLE ledger_read_app   LOGIN PASSWORD '<LEDGER_READ_APP_PASSWORD>';
  GRANT borjie_ledger_reader   TO ledger_read_app;
  # then set LEDGER_DATABASE_URL / LEDGER_DATABASE_URL_READONLY with those creds.
  # The two passwords were written to $ENV_FILE_NAME as
  # LEDGER_ENGINE_APP_PASSWORD / LEDGER_READ_APP_PASSWORD.

[FLAG default-off] BORJIE_* cognitive gates stay OFF until a staging canary.
---------------------------------------------------------------------------
CHECKLIST
